### ISSUE TITLE
docs: Initialize README.md file.

### ISSUE THREAD

**Issue by mayburgos** [anitab-org/bridge-in-tech-backend#1]
## Description
As a contributor,
I need to learn about the project,
so that I can collaborate with others on its development.

## Mocks
```
# bridge-in-tech-android


## Contributing

**This project is under active development**

Please read our [Contributing Guidelines](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/CONTRIBUTING.md), [Code of Conduct](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/CODE_OF_CONDUCT.md) and [Reporting Guidelines](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/REPORTING_GUIDELINES.md) thoroughly.

## Branches

- **master**: This branches contain the deployment of the backend.
- **develop**: This contains the latest code. All the contributing PRs must be sent to this branch.

## Contact

If you have any questions or want to discuss something about this repo, feel free to join our [Zulip Community](http://anitab-org.zulipchat.com/). If you are a new contributor, head over to this project's stream [#bridge-in-tech](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech) on Zulip to see ongoing discussions.

## License

The project is licensed under the GNU General Public License v3.0. Learn more about it in the [LICENSE](https://github.com/anitab-org/anitab-org.github.io/blob/develop/LICENSE) file.
```

### Update [Required]
- [ ] Include the minimum details that were included in the **Mocks** section above.
### Enhancement to Update [Optional]
- [ ] Reach out to @mtreacy002 for a description of the project!

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by menina763** [comment]
Hello! Could I perhaps take on this issue?

**Comment by mayburgos** [comment]
@Menina294 Yes! Go ahead and feel free to ping @mtreacy002 for a proper description. I couldn't come up with one. :)

**Comment by menina763** [comment]
Alrighty!
@mtreacy002 , do you happen to know what I should include for the description?
Wait, should I ping in Zulip?

**Comment by mtreacy002** [comment]
Thanks, for taking up the issue, @Menina294. you're officially the first contributor to the project 🎉.
I can answer here (or reach me out on Zulip bridge-in-tech stream if I take some time to answer here, coz browsing emails not as easy as browsing Zulip, I guess 😂 ). I have a brief info on the [project proposal](https://docs.google.com/document/d/1ZZCOoWdn2yb6N3qrrgK0SRDQPcx2Pp7kz3yDXDRSHUs/edit) that you can put as an overview of the project. I also have another 'brief- er' version of the project on my [blog intro](https://medium.com/@mtreacy002/intro-to-google-summer-of-code-2020-with-anitab-org-open-source-d89dd5b32b5d?sk=24531569d7757f865ddf11f2a11599e3).
Feel free to play with the wordings as long as its inline with the spirit of the project 😉. 
Let me know if you need further assistance 😃.

**Comment by menina763** [comment]
Alrighty, thanks @mtreacy002 !

**Comment by mtreacy002** [comment]
For setting up, I will have to wait for the meeting with mentors first to finalise the platform and architecture. But will keep you updated on Zulip [bridge-in-tech stream](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech) on this 😉

**Comment by menina763** [comment]
Alrighty, I finished typing the README.md file. Should I add it here?

**Comment by mtreacy002** [comment]
> Alrighty, I finished typing the README.md file. Should I add it here?

Definitely, @Menina294. You can open a PR to address this issue, so we (both of us and other contributors) can review it together 😉 . Let me know if you need some help 👍

**Comment by menina763** [comment]
Yeah, I think I might need some help with opening a PR since I've never done that before 😅

**Comment by mtreacy002** [comment]
No worries, @Menina294. I'm here to help 😉 

So, on the top navbar you could click on Pull requests 
<img width="731" alt="Screen Shot 2020-05-07 at 1 23 05 pm" src="https://user-images.githubusercontent.com/29667122/81251132-eec1db00-9065-11ea-9ea4-2de01b642296.png">

click on the `New Pull Request` button (green one on the left)

then pls copy paste the Pull request template to the body of the repo.

```
### Description

<!--- Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change. --->

Fixes # [ISSUE]

### Type of Change:

<!--- **Delete irrelevant options.** --->

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)



### How Has This Been Tested?

<!-- Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test. -->


### Checklist:

<!-- **Delete irrelevant options.** -->

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules
```

**Comment by mtreacy002** [comment]
on `Fixes # [ISSUE]`, replace '# [ISSUE]' with the issue number you are working on (in this case' #1'

**Comment by mtreacy002** [comment]
For the title of the PR, please follow the commit guidelines [here](https://github.com/anitab-org/mentorship-backend/wiki/Commit-Message-Style-Guide) to choose the right message you should use as the commit message.
As for the PR title, I normally use the format: <tag>: <#Issue number> <brief description of what the PR is about>. Keep the description short and concise, possibly no longer than 35 characters long?

**Comment by menina763** [comment]
Hmm, when I clicked on the "New Pull Request" button, I was taken to a Comparing page. Did I click somewhere wrong?

**Comment by mtreacy002** [comment]
Sorry, my bad, I forgot to ask, have you commit your code changes and push to the remote repository from your IDE?

**Comment by mtreacy002** [comment]
I can guide you if you're not sure how to

**Comment by menina763** [comment]
Nope, I haven't done that yet, and yes I would appreciate it if you would guide me!

**Comment by mtreacy002** [comment]
> Nope, I haven't done that yet, and yes I would appreciate it if you would guide me!

Cool.. Can you tell me which IDE you are using, pls?

**Comment by menina763** [comment]
I don't know if it counts as an IDE, but I was using a extension on Google Chrome called "Markdown Editor"

**Comment by mtreacy002** [comment]
Also, can you please tell me what's the step you take when cloning this repository? Have you fork this repo and open it on an IDE?

**Comment by menina763** [comment]
No, I was too afraid to clone it or fork it 😅

**Comment by mtreacy002** [comment]
It's ok, one step at a time. I felt like that too when I was a beginner...😂 

But then I found out, cloning won't create any damage to your system. Same concept actually used for copy pasting. We never have to worry about the impact. 😆 
Anyway, you could put this issue on hold for now (we're in no hurry) and try this [GitHub guidelines/tutorial](https://github.com/firstcontributions/first-contributions) first to get use to the forking, cloning and contributing to the repository. I did this too for when I first trying to contribute to open source. I found this resource is very helpful. Still, don't hesitate to ask me on anything if you have doubt 😉

**Comment by mtreacy002** [comment]
Also, don't forget to save the file you've already work on in a .md format so it's ready to be used once you know and have cloned this repo to your IDE. I'll help you along until you're comfortable finding your way around GitHub 😉

**Comment by mtreacy002** [comment]
Just curious, which IDE you're thinking of working on for this repo? I'm using VSCode, but everyone can use whichever IDE they preferred

**Comment by menina763** [comment]
I haven't used any IDE's in a loong time, so I guess I'll try VSCode. Hopefully it doesn't take too long to download!

**Comment by mtreacy002** [comment]
It shouldn't be. I'm not sure how long it'll take to download (I did that a while ago), but it'll a good alternative to have among all other great IDE out there. So, it'll be worth it. 😀

**Comment by menina763** [comment]
Alrighty, I think due to my internet downloading VSCode will take a while, but in the meantime I'll try to follow along with the tutorials you linked. Thanks for helping me out by the way, and I'll reach out again if I need some assistance 😄!

**Comment by mtreacy002** [comment]
> Alrighty, I think due to my internet downloading VSCode will take a while, but in the meantime I'll try to follow along with the tutorials you linked. Thanks for helping me out by the way, and I'll reach out again if I need some assistance 😄!

Will be here for you .... see you later 👋

**Comment by menina763** [comment]
Alrighty, I managed to submit my first PR! It wasn't as scary as I thought it would be 😅. Could you please check it and make sure that I submitted it right?

**Comment by mtreacy002** [comment]
> Alrighty, I managed to submit my first PR! It wasn't as scary as I thought it would be 😅. Could you please check it and make sure that I submitted it right?

Well done, @Menina294. I'm proud of you for taking the first step for contributing to open source 🚀 💃🥰. I'll review your PR and give you my feedback there 😉 .
