### ISSUE TITLE
Planning: BridgeInTech App Flow

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#10]
App flow as per proposal:
[Link to online document](https://drive.google.com/open?id=1Cxa3l449Odpb3XMeghrH1W01I7ScVLTV)

Opt. 3. MS+BIT schemas in MS DB+REST

![BridgeInTech - App Flow MS+BIT schemas in MS DB+REST.png](https://images.zenhubusercontent.com/5eb4e4b9636d69f8661b2c28/9d71e8de-02cb-4ddc-8f9a-1c533cf6b424)

**Comment by mtreacy002** [comment]
Hi team (@isabelcosta, @ramitsawhney27, @foongminwong).

I've made some adjustments to the App Flow based on @ramitsawhney27 suggestion. 

**Option 1:**
This adjustment is made under assumption that the application would have 2 databases MS+BIT with one REST API.

Below is the screenshot of new flow. ([link to file](https://drive.google.com/file/d/1Cxa3l449Odpb3XMeghrH1W01I7ScVLTV/view?usp=sharing))

<img width="1063" alt="Screen Shot 2020-05-12 at 12 37 56 pm" src="https://user-images.githubusercontent.com/29667122/81632388-708e7b80-944d-11ea-9f66-da353a6f448d.png">

**Comment by mtreacy002** [comment]
**Option 2:**
For this option, the assumption is the BridgeInTech application will use MS DB + API with BIT DB + API.

<img width="1066" alt="Screen Shot 2020-05-12 at 4 39 40 pm" src="https://user-images.githubusercontent.com/29667122/81646909-6da48280-946f-11ea-8aa6-2b20b770edc9.png">

To think about:
* Is it possible for one API to talk to 2 different DB? If so, how can we achieve this (routing?)? If not, should we use 2 APIs instead? 
* What about performance impact of using them (either 2 DBs + 1 API or 2 DBs + 2 APIs)? 
* Which one will have the least of [N +1 problem (not creating loop full of requests)](https://nordicapis.com/making-fast-apis-lessons-learned-from-40-years-of-sql/)?

**Comment by foongminwong** [comment]
> Hi team (@isabelcosta, @ramitsawhney27, @foongminwong).
> 
> I've made some adjustments to the App Flow based on @ramitsawhney27 suggestion.
> 
> **Option 1:**
> This adjustment is made under assumption that the application would have 2 databases MS+BIT with one REST API.
> 
> Below is the screenshot of new flow. ([link to file](https://drive.google.com/file/d/1Cxa3l449Odpb3XMeghrH1W01I7ScVLTV/view?usp=sharing))
> 
> <img alt="Screen Shot 2020-05-12 at 12 37 56 pm" width="1063" src="https://user-images.githubusercontent.com/29667122/81632388-708e7b80-944d-11ea-9f66-da353a6f448d.png">
> 
> To think about:
> 
> * Is it possible for one API to talk to 2 different DB? If so, how can we achieve this (routing?)? If not, should we use 2 APIs instead? What about performance impact of using 2 database with one API?

Hmm, based on what I understood from @ramitsawhney27 idea, I believe it would be 1 database that branches out 2 schemas (MS Schema and BIT Schema). Will further discuss and get clarification during our all team's meeting 💻

**Comment by mtreacy002** [comment]
**Update:** Option 4.
Hi @isabelcosta, @ramitsawhney27, and @foongminwong. I've adjusted option 2 App Flow as per discussion on Team Weekly Meeting, May 13th. I appreciate If you all can confirm that this is our direction. You can post a comment or react with ✅ .
In the mean time  I'm going to work on the ERD [issue#12](https://github.com/anitab-org/bridge-in-tech-backend/issues/12) so we can finalize database design 😉 .

<img width="1301" alt="Screen Shot 2020-05-14 at 7 49 03 am" src="https://user-images.githubusercontent.com/29667122/81869632-bbc49d80-95b7-11ea-8f69-a50a4fde70a1.png">


[Link to file](https://drive.google.com/file/d/1Cxa3l449Odpb3XMeghrH1W01I7ScVLTV/view?usp=sharing), also available on BridgeInTech Google drive folder: **BridgeInTech_MTreacy002_Presentation.drawio**

**Comment by mtreacy002** [comment]
**Update** Option 5
Hi @anitab-org/bridgeintech-maintainers. Here's another option with BIT API facing frontend and BIT backend will call MS API to get MS related data.

<img width="1253" alt="Screen Shot 2020-05-16 at 10 02 46 pm" src="https://user-images.githubusercontent.com/29667122/82119385-62c85580-97c1-11ea-8796-ab855feacb89.png">

**Comment by ramitsawhney27** [comment]
@mtreacy002 - As discussed, can you please update the two schemas to be shown under the same database? The rest looks good!

**Comment by mtreacy002** [comment]
Update on Option 5.
@ramitsawhney27 , is this ok?

![Screenshot (1)](https://user-images.githubusercontent.com/29667122/82150765-5664fb00-989c-11ea-97ed-84da7a54c0c9.png)

**Comment by isabelcosta** [comment]
@mtreacy002 a nice to have would be mention of the APIs scope, so which is for MS and for BIT

**Comment by mtreacy002** [comment]
Update:
Hi @anitab-org/bridgeintech-maintainers, here's the update on option 5, now with API names as discussed in the BIT Team weekly meeting May 20th AEST.

<img width="1274" alt="Screen Shot 2020-05-21 at 6 21 12 am" src="https://user-images.githubusercontent.com/29667122/82493563-8544d080-9b2b-11ea-8016-f87273443378.png">

[link to file](https://drive.google.com/file/d/1Cxa3l449Odpb3XMeghrH1W01I7ScVLTV/view?usp=sharing)

**Comment by mtreacy002** [comment]
Update:

As per our discussion on BIT Weekly Meeting, Wednesday, May 27th, the following will apply during GSoC periods:
* On initial stage and during early development of GSoC, the App Flow on initial option 5 as posted [here](https://github.com/anitab-org/bridge-in-tech-backend/issues/10#issuecomment-629635500) will be the one to be used


<img width="1253" alt="Screen Shot 2020-05-16 at 10 02 46 pm" src="https://user-images.githubusercontent.com/29667122/82119385-62c85580-97c1-11ea-8796-ab855feacb89.png">

* At the final stage of GSoC, hopefully we can achieve the final version of option 5 as posted [here](https://github.com/anitab-org/bridge-in-tech-backend/issues/10#issuecomment-631705821)

<img width="1274" alt="Screen Shot 2020-05-21 at 6 21 12 am" src="https://user-images.githubusercontent.com/29667122/82493563-8544d080-9b2b-11ea-8016-f87273443378.png">

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers , Closing this as the app architecture has matched the final stage targetted [here](https://github.com/anitab-org/bridge-in-tech-backend/issues/10#issuecomment-635048077)
