### ISSUE TITLE
QA: Personal Details API returns password_hash of user | CROSS-PROJECT-ISSUE

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-backend#102]
**Describe the bug**
The GET call for /user/personal_details returns password_hash of user in response body. It is sensitive information, and should not be returned as payload. 

**To Reproduce**
1. Login into bridge-in-tech
2. Click on Space -> Personal Details
3. Open the Network tab on the dev tools
4. See the payload returned for this GET call - /user/personal_details

**Expected behavior**
Password_hash should not be a part of the response body 

**Screenshots**
<img width="1440" alt="Screen Shot 2020-08-09 at 5 21 54 PM" src="https://user-images.githubusercontent.com/14279061/89731473-deeed400-da64-11ea-8ca9-e6ed176c7ab7.png">

**Comment by meenakshi-dhanani** [comment]
@mtreacy002 is this because of the Mentorship API we use directly? Then I'll open an issue on mentorship backend as well

**Comment by mtreacy002** [comment]
Note: This is a cross-project issue with Mentorship System backend. I have opened the corresponding issue [#790](https://github.com/anitab-org/mentorship-backend/issues/790) on Mentorship Backend for the same bug.

**Comment by mtreacy002** [comment]
Update: This issue is now ready for anyone to claim since the corresponding issue on Mentorship System backend ([#790](https://github.com/anitab-org/mentorship-backend/issues/790)) already been fixed through [PR819](https://github.com/anitab-org/mentorship-backend/pull/819). Similar approach can be taken on the BIT side.

**Comment by Aaishpra** [comment]
@mtreacy002 do we have to just remove the password hash field , like the mentioned PR . If yes, i would like to take this up.

**Comment by mtreacy002** [comment]
@Aaishpra you are correct, you just need to remove the password hash field from the user API models. I'll assign this to you then 😉

**Comment by Aaishpra** [comment]
Thanks @mtreacy002 for clarifying,also I have submitted the PR , review it when you get time.
