### ISSUE TITLE
Dev: Refactor login to return user is_organization_representative status

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#111]
## Description
As a student,
I need refactor login to return user is_organization_representative status,
so that I can direct user to the appropriate Navigation bar on UI depending on this status.

## Mocks
<img width="1557" alt="Screen Shot 2020-08-17 at 11 59 08 am" src="https://user-images.githubusercontent.com/29667122/90353312-36a2c600-e089-11ea-82da-ba519b057304.png">

### Update [Required]
- [ ] return `is_organization_representative` as part of login response

### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by meenakshi-dhanani** [comment]
Modified the frontend workflow to display organization profile if an error isn't received. Also modifying the login API to return user specific details wasn't the right thing to do. Hence I am closing this issue.
