### ISSUE TITLE
Dev: Refactor date fields on endpoints to use a human readable format

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#115]
## Description
As a GSoC student,
I need refactor all the date fields on API endpoints to use RFC 2822,
so that I can shift the logic for date conversion to be at the backend instead of frontend.

## Mocks
NA

### Update [Required]
- [ ] Refactor all existing date fields to use RFC 2822 (e.g. Thursday, 31-Dec-20 00:00:00 UTC)

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by 19-pragya** [comment]
can i work in this??

**Comment by mtreacy002** [comment]
@19-pragya . This issue is labeled GSoC which means meant to be done by student (me 😁). Perhaps, if @anitab-org/bridgeintech-maintainers mentors have different opinion on this, we can take off the label GSoC and you can work on this (so I can continue with the rest of GSoC deliverables). @isabelcosta and @ramitsawhney27 , can we have your opinion on this? Thanks

**Comment by mtreacy002** [comment]
@19-pragya . My mentor @ramitsawhney27 has given his response [here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/New.20Issues/near/207407227). This PR is kept for GSoC only, so I'll work on this. But thanks for showing your interest on contributing to the project. I encourage you to contribute to the project with another open PR either on backend or [frontend](https://github.com/anitab-org/bridge-in-tech-web/issues) 😉
