### ISSUE TITLE
Test: PUT /organizations/{organization_id}/programs/{program_id} endpoint

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#128]
## Description
As a developer,
I need write test cases for PUT /organizations/{organization_id}/programs/{program_id} endpoint,
so that I can make sure that the endpoint works as it should be.

## Mocks
NA

### Update [Required]
- [ ] test update program with successful outcome (response 200)
- [ ] test update program with at least 2 error responses from 4XX

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by devkapilbansal** [comment]
@mtreacy002 I want to look into the issue

**Comment by mtreacy002** [comment]
Sure, I'll assign this issue to you @KapilBansal320. 😉

**Comment by devkapilbansal** [comment]
Thanks, I will make a pull request as soon as possible.

**Comment by mtreacy002** [comment]
@KapilBansal320 . Can you please give an update on your progress?

**Comment by devkapilbansal** [comment]
Yes, I was going through the code first. Will make a pull request within this week

**Comment by devkapilbansal** [comment]
Hi, I try to setup and run the code. But getting error as:
![Screenshot from 2020-09-09 22-25-03](https://user-images.githubusercontent.com/42766576/92629055-5bd2cf00-f2eb-11ea-97b3-02926109234b.png)

I tried my level best to solve this error. It would be my pleasure if you can help me with this

**Comment by mtreacy002** [comment]
@KapilBansal320 , can you tell me in which step of the setup instructions you got this error? Also, setup instructions have been modified recently, especially on [step 7 creating .env](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup#7th-create-the-env-file-using-envtemplate). There is some extra steps for linux and windows machines that contributors need to do to make the connection to postgresql works (from the error message, I'm guessing that's what causing it). Can you please give it a try? Let me know how you go.

**Comment by devkapilbansal** [comment]
I got this issue on step 7 itself when running `python run.py`. 
Here is my environment file.

![save](https://user-images.githubusercontent.com/42766576/92689781-4b5b3c80-f35d-11ea-8ba0-d0cad1972d8f.png)

**Comment by mtreacy002** [comment]
@KapilBansal320  can you tell me what type of OS you're using? Mac, Windows or Linux?

**Comment by devkapilbansal** [comment]
Linux:Ubuntu

**Comment by mtreacy002** [comment]
Ok, have you tried to uncomment line 88 and comment out line 86 under `LocalConfig` in the config.py as per the updated setup instructions? Also, I can see that you are using `dev` env. you need to use that line 88 with `local` as env. Please try and let me know.

**Comment by mtreacy002** [comment]
Also, there are 4 options you can use for DB_TYPE as mentioned in the setup instructions. From [one of the contributors experience](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Dev.20Env.20Setup/near/209286678) whom also using linux machine, she's successfully completed the setting up using `postgres+psycopg2` option.

**Comment by devkapilbansal** [comment]
Thanks, I solved it by adding DB_REMOTE_URL in my environment file.

**Comment by mtreacy002** [comment]
That's great. Although, please be aware that after [PR#125](https://github.com/anitab-org/bridge-in-tech-backend/pull/125) is approved and merged, DB_REMOTE_URL will no longer be used as it will be replaced with db credentials that will be concatenated as the string db_uri using build_db_uri() method (which was also why i suggested the fix option [above](https://github.com/anitab-org/bridge-in-tech-backend/issues/128#issuecomment-690021653)). So, don't forget to change your .env again after PR #125 is merged 😉.

**Comment by devkapilbansal** [comment]
Hi @mtreacy002 , I want to ask why c_name and c_email are used here.
https://github.com/anitab-org/bridge-in-tech-backend/blob/fbad596538609972acd3b8f77b2b73d3be912aad/app/database/models/bit_schema/organization.py#L105-L112

**Comment by mtreacy002** [comment]
> Hi @mtreacy002 , I want to ask why c_name and c_email are used here.
> 
> https://github.com/anitab-org/bridge-in-tech-backend/blob/fbad596538609972acd3b8f77b2b73d3be912aad/app/database/models/bit_schema/organization.py#L105-L112

Good pick up, @KapilBansal320 . They were originally named with that c_name and c_email, but I changed the names in the model but might have forgotten to change thee db query as well. Can you open an issue for that?

**Comment by devkapilbansal** [comment]
Sure, I will open a issue and solve it first before moving forward

**Comment by devkapilbansal** [comment]
Opened issue #135 for that

**Comment by devkapilbansal** [comment]
Also, can you please tell me why I am getting 400 response here.

I try to create a program first before updating
![program](https://user-images.githubusercontent.com/42766576/93017323-52947b80-f5e5-11ea-9d35-5fea45086897.png)

**Comment by mtreacy002** [comment]
@KapilBansal320 . from your screenshot above I could see a couple of things that could potentially be the cause. To know which one  of the below actually causing it, you can try to debug and see what the error message is for that HTTP error 400:
* the payload must be as specified in the `update_program_request_model` (in app/api/models/organization.py), even if you have some empty fields. This is because there is a validation check that will check if your payload contains the expected fields of the request model. If not, the request will be rejected. The method can be found inside `app/utils/validation_utils.py`.
<img width="795" alt="Screen Shot 2020-09-14 at 8 08 08 am" src="https://user-images.githubusercontent.com/29667122/93029869-d8eea300-f661-11ea-9155-5dedc7678c38.png">

* start date and end date need to be in human readable format with pattern specified in the `update_program_request_model` (in app/api/models/organization.py)
<img width="1105" alt="Screen Shot 2020-09-14 at 12 27 20 am" src="https://user-images.githubusercontent.com/29667122/93020571-2bf43600-f621-11ea-9de5-e92e8364ba72.png">
* target candidate is actually saved in the database as jsonb object that is built from list of specific target candidates attributes in the payload.

- in the database:
<img width="1210" alt="Screen Shot 2020-09-14 at 12 30 38 am" src="https://user-images.githubusercontent.com/29667122/93020769-5a264580-f622-11ea-80ef-95b5aec0e5d3.png"> 
- in the program dao logic:
<img width="1101" alt="Screen Shot 2020-09-14 at 12 59 19 am" src="https://user-images.githubusercontent.com/29667122/93021395-b179e500-f625-11ea-89c4-698fe752d3d4.png">

- in the request model:
<img width="798" alt="Screen Shot 2020-09-14 at 12 34 36 am" src="https://user-images.githubusercontent.com/29667122/93020764-4ed31a00-f622-11ea-97e0-bb13614982f5.png">

So, since you are using payload to test the API endpoint, you need to put actual target candidate attributes because otherwise the payload will be rejected because there is no payload with the name `target_candidate` in the api request model.

* If you checked again the API request model, you could see that `creation_date` is not something that user can define. The value of this attribute coming from logical computation when the program instance is created by the database, so you shouldn't put in inside the payload (line 94 your code).
<img width="755" alt="Screen Shot 2020-09-14 at 12 44 47 am" src="https://user-images.githubusercontent.com/29667122/93020977-a920aa80-f623-11ea-806c-e2eeebf05fa5.png">

If you still confuse, you could check my PR #130 on test create program and see how I've done it there. 

Note: to complete this PR, you do not need to write the test for create program. You could prepare an existing program data inside the test database (see how I've done it in PR #129 and focus on writing test on the update program functionality.

Let me know if you still have doubts 😉

**Comment by devkapilbansal** [comment]
@mtreacy002 Since I have made a pull request for this issue, can I get assigned for others?

**Comment by mtreacy002** [comment]
@KapilBansal320 , can you address the feedback I made on PR #137 first? 
Also, It's always good to have a `cool off` period after you submitted a PR (at least 24 hours while waiting for the reviewer to give their feedback) to reflect on whether or not the code change you made needs some improvement. Then there are also other ways to contribute while waiting for your PR is being reviewed. 
For example, you can test the app flow/logic to see if there're bugs or areas in the code or documentations that can be improved and report them by opening issues. Another way is to help review open PRs that are waiting for a review. We have quite a few that's been waiting for quite a while for reviewers to look at the code. These examples are great ways to help you becoming an all-rounded contributor to Open Source 😉.
Regardless, I'm very happy to see that you are keen to contribute to this project. Look forward to work together with you to improve the contributors engagement to the project 👍

**Comment by devkapilbansal** [comment]
Okay thanks, I will remember it for future.
