### ISSUE TITLE
Planning: Entity Association Model

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#13]
[As per proposal](https://docs.google.com/document/d/1ZZCOoWdn2yb6N3qrrgK0SRDQPcx2Pp7kz3yDXDRSHUs/edit#heading=h.1pxezwc):

![BridgeInTech - EAM.png](https://images.zenhubusercontent.com/5eb4e4b9636d69f8661b2c28/e69f1c01-cab6-486b-a608-8238fddae78c)

**Comment by mtreacy002** [comment]
Idea for improvement:

After the Final Proposal due date of GSoC20 (May Mar 31st), I decided for a Company to have a representative who is a User. With this idea in mind, I adjusted the EAM to the following:

<img width="776" alt="Screen Shot 2020-05-06 at 10 30 28 pm" src="https://user-images.githubusercontent.com/29667122/81524584-031f1400-9395-11ea-938d-fa2687bcb6db.png">

[Link to file](https://app.lucidchart.com/invitations/accept/802a6d9b-a2c5-441c-b942-d2eb06d40a7b)

**Comment by ramitsawhney27** [comment]
This looks good.

**Comment by mtreacy002** [comment]
Update:
Hi @anitab-org/bridgeintech-maintainers, here's the 
Entity Association Model as per discussion on BIT Team meeting, May 20th AEST.

<img width="785" alt="Screen Shot 2020-05-21 at 6 15 19 am" src="https://user-images.githubusercontent.com/29667122/82493131-c688b080-9b2a-11ea-8586-c4f02a182e0b.png">

**Comment by mtreacy002** [comment]
Update:
Hi @anitab-org/bridgeintech-maintainers. Just wanna give you an updated version of Entity Association Models (hopefully the final one as far as MVP concern)

![Screen Shot 2020-05-28 at 11 53 34 am](https://user-images.githubusercontent.com/29667122/83089600-0971f780-a0da-11ea-8591-60181626f9d0.png)

**Comment by mtreacy002** [comment]
Closing this as it's completed with the last comment.
