### ISSUE TITLE
DOC: Update ENV_SETUP_INSTRUCTION.md to match Wiki Dev setup instructions.

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#131]
## Description
As a developer,
I need to update ENV_SETUP_INSTRUCTION.md on .github folder,
so that I can be sure that the information on that doc match the instruction on [wiki backend repo](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup).

## Mocks
NA

### Update [Required]
- [ ] update the content of ENV_SETUP_INSTRUCTION.md with the content on [BIT Backend development environment setup Instructions WIKI](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup)

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hour

**Comment by radhikasethi2011** [comment]
I wish to work on this issue. Please assign it to me.

**Comment by mtreacy002** [comment]
Sure, @radhikasethi2011 . I'm assigning you now.

**Comment by mtreacy002** [comment]
@radhikasethi2011 , can you please give me an update on your progress?

**Comment by mtreacy002** [comment]
@radhikasethi2011 , I'm going to make this issue available again since I haven't received an update for a while.
