### ISSUE TITLE
Bug: Rename variables c_name and c_email

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/bridge-in-tech-backend#135]
**Describe the bug**
In the ogranization model, c_name and c_email are used in functions that are not defined

**To Reproduce**
Try to use **find_by_name** or **find_by_email** function on Organization Model

https://github.com/anitab-org/bridge-in-tech-backend/blob/fbad596538609972acd3b8f77b2b73d3be912aad/app/database/models/bit_schema/organization.py#L105-L112

**Additional context**
In the find_by_name and find_by_email functions, search query is looking for c_name and c_email but they are renamed to name and email.

**Comment by mtreacy002** [comment]
@KapilBansal320 , can you please use one of the templates given by anitab.org (when you click on the `New Issues` button to create new issue, you'll see 4 templates below). This is required from contributors as mentioned in the [Contributing Guidelines](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/CONTRIBUTING.md) which you can find from [Getting started](https://github.com/anitab-org/bridge-in-tech-backend/wiki/Getting-Started) wiki
<img width="969" alt="Screen Shot 2020-09-14 at 8 19 22 am" src="https://user-images.githubusercontent.com/29667122/93030026-38997e00-f663-11ea-8bd4-3bdddd9a6cdd.png">

In your case, you need to use the `Bug report` template.

**Comment by devkapilbansal** [comment]
@mtreacy002 I used the above bug report template for this now.

**Comment by mtreacy002** [comment]
@KapilBansal320, may I know the reason why you are not replacing it with the bug template set by AnitaB.Org? Just so it's clear for us here in AnitaB.Org to why contributors choose to use their own template. cc @anitab-org/coding-team and @anitab-org/bridgeintech-maintainers

**Comment by mtreacy002** [comment]
But now that I look again, It makes sense, since this is not actually a bug needing a screenshot. so, It's ok for now, @KapilBansal320. cc @anitab-org/coding-team and @anitab-org/bridgeintech-maintainers , hope this is ok with you all too 😉
