### ISSUE TITLE
Doc: Create GETTING_STARTED.md file inside .github folder

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#142]
**Is your feature request related to a problem? Please describe.**
The [Getting Started](https://github.com/anitab-org/bridge-in-tech-backend/wiki/Getting-Started) page on the bridge-in-tech-backend wiki is currently not written as a markdown document, but directly written as a wiki page. The content on this page needs to be made available to contributors so they can also involve in improving the page documentation.

**Describe the solution you'd like**
Create a markdown file `GETTING_STARTED.md` inside `.github` folder and place the content on the  [Getting Started](https://github.com/anitab-org/bridge-in-tech-backend/wiki/Getting-Started) page inside that doc so that the wiki sidebar can refer to the doc instead of having the content written as a wiki page.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by anishghimire603** [comment]
Can you assign this to me. I would like to work on this issue.

**Comment by mtreacy002** [comment]
Sure, @anishghimire603. I'll assign you now. Thank you for picking up the issue 😉

**Comment by anishghimire603** [comment]
@mtreacy002 i have to place the content of <a href = "https://github.com/anitab-org/bridge-in-tech-backend/wiki/Getting-Started"> Getting Started </a> inside the <code> GETTING_STARTED.md </code> right? or I have make changes in wiki page?

**Comment by anishghimire603** [comment]
@mtreacy002  can I clone wiki page and copy the content of there and put it in .github/GETTING_STARTED.md  ?

**Comment by mtreacy002** [comment]
Sorry I couldn't get back to you quickly, @anishghimire603. I went to prepare and have lunch with the family 😁. But I could see that you'd solved it yourself. I've approved your PR 🎉

**Comment by anishghimire603** [comment]
> Sorry I couldn't get back to you quickly, @anishghimire603. I went to prepare and have lunch with the family 😁. But I could see that you'd solved it yourself. I've approved your PR 🎉

Its okay @mtreacy002 when it will be merged?

**Comment by mtreacy002** [comment]
As soon as you make the title change, I'll merge it 😁

**Comment by anishghimire603** [comment]
> As soon as you make the title change, I'll merge it 😁

@mtreacy002 have a look @ #144
