### ISSUE TITLE
Doc: Add python 3.x badge to README

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#146]
## Description
As a contributor,
I need see the Python badge with version number,
so that I know which Python version to use with the application.

## Mocks
NA

### Update [Required]
- [ ] Add badge with Python 3.x version in the README

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Additional Note** 
see example on how it was done on MS backend [PR#718](https://github.com/anitab-org/mentorship-backend/pull/718). However, no need to specify the decimal number, just use `x` for `3.x`

**Comment by anishghimire603** [comment]
can I  work on this  issue?

**Comment by mtreacy002** [comment]
@anishghimire603 , you have made your first contribution to the repo with PR #144. You can look for other issues that is not labelled `First-timers-only` issue. I'll leave this one for any new contributor.

**Comment by DivyaR12** [comment]
Hi 
I would like to work on this issue as a first-timer

**Comment by mtreacy002** [comment]
Sure, @DivyaR12 . I'll assign you to this.

**Comment by kritikaparmar-programmer** [comment]
Hey @mtreacy002 I'm first timer here.. Can I contribute to this issue?

**Comment by mtreacy002** [comment]
@kritikaparmar-programmer , @DivyaR12 is currently assigned to this. @DivyaR12 , can you please give us an update on where you are with this task? I haven't seen a PR open for this yet.

**Comment by DivyaR12** [comment]
@mtreacy002 I am done with the task but I am having issues in committing the changes and creating a new PR.

**Comment by mtreacy002** [comment]
@DivyaR12 , for me to be able to help, can you please tell me what the issue is?

**Comment by DivyaR12** [comment]
After forking the repo, and cloning it, I end up having 3 branches for some reason- origin, master and the new branch I created for the issue. Remote setup was also done according the instructions in the Wiki. I tried to have the develop branch and the created a new branch under it as well for the issue. In both cases I get error for access rights when I try using git push.

**Comment by mtreacy002** [comment]
I see... Let's go through this one at a time:
To explain what's happening...
> After forking the repo, and cloning it, I end up having 3 branches for some reason- origin, master and the new branch I created for the issue.

This is expected, after cloning, you should see master and develop branch (2 branches). Then you said you created another branch for the issue (this is the right thing to do, since you are not suppose to work on issue from develop branch).

> Remote setup was also done according the instructions in the Wiki. I tried to have the develop branch and the created a new branch under it as well for the issue. In both cases I get error for access rights when I try using git push.

You don't /can't do this since you are not the maintainer/owner of the anitab remote "upstream" repo. So, this remote "upstream" repo cannot be modify by anyone that has no access. So, the error you've seen is expected.

Now the way so you can push your code change from your pr branch to the repo
After performing all the fork, clone, setup remote, you need to make sure on you are on the develop branch as the starting point 

<img width="530" alt="Screen Shot 2020-09-27 at 10 31 10 am" src="https://user-images.githubusercontent.com/29667122/94352782-af476a00-00ac-11eb-87f2-2cf47d2ff3aa.png">

For setting up the backend servers, you can read the instructions wiki. If you have doubt, feel free to ask me.

But for now, let's checkout to the PR branch you've created. Once you've done making the needed change, commit and push to the origin repo. This will automatically create the same PR branch on your remote fork ("remote origin") repo. Remember, the main anitab repo is referred to as "remote upstream" repo. 

After you push to origin, you can go to your github browser and you'll see a highlighted box notifying you've just pushed changes to the repo. Click on `Compare` to open a PR template and write description of that issue you are working on. Once done, your PR will be listed in the PRs list on the main anitab github repo.

Hope this helps 😉

**Comment by mtreacy002** [comment]
@DivyaR12 , can you please give an update on this issue?

**Comment by anishghimire603** [comment]
Can I work on this issue?

**Comment by madhhuurrii** [comment]
@mtreacy002 if this issue is available, can u please assign me as I am a firsttimer in this repo?

**Comment by DivyaR12** [comment]
@mtreacy002 I am working on it and should be done in a few hours.

**Comment by mtreacy002** [comment]
@DivyaR12 . Can you please give me an update on this issue?

**Comment by harsh1868-zz** [comment]
@mtreacy002  someone is working on this issue but still, he/she has not given any response and I already try to add and make a pull request but as it's assign to other my request is failing in compile time so please assign to me or ask @DivyaR12  to complete it.

**Comment by mtreacy002** [comment]
@harsh1868 , I think I can safely assign you to this now as @DivyaR12 didn't give her update.

**Comment by harsh1868-zz** [comment]
@mtreacy002  Please review again and ask me if any changes else merge.
