### ISSUE TITLE
Doc: Add Build badge for Travis CI build to README

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#147]
## Description
As a contributor,
I need to see Build badge,
so that I can see the status of the latest Travis CI build.

## Mocks
NA

### Update [Required]
- [ ] Add Build badge for Travis CI build. [Refer to the following resource on how to do it](https://docs.travis-ci.com/user/status-images/)

### Enhamcement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by AltCtrlDel1999** [comment]
I would like to work on this issue

**Comment by mtreacy002** [comment]
Sure, @AltCtrlDel1999 , I'll assign you to this.
