### ISSUE TITLE
Doc: Add CodeCov badge to README

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#148]
## Description
As a contributor,
I need to see the CodeCov badge on README,
so that I know the percentage of code being covered by the test cases.

## Mocks
NA

### Update [Required]
- [ ] Add CodeCov badge to README. Refer to [this](https://stackoverflow.com/questions/54010651/codecov-io-badge-in-github-readme-md) resource on how to do it.

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by khushishikhu** [comment]
may i take this issue

**Comment by mtreacy002** [comment]
sure, @khushishikhu . I'll assign you to this.
