### ISSUE TITLE
For Windows OS users

### ISSUE THREAD

**Issue by Hinal-Srivastava** [anitab-org/bridge-in-tech-backend#159]
### **7th, Create the .env file using .env.template**
For Windows OS users the commands will generate the following error: 
`'export' is not recognized as an internal or external command, operable program or batch file.`
This is because as the '**export**' command is valid only for Unix shells, hence see should use "**set**" instead of "**export**"

**Comment by Aju100** [comment]
Hi @Hinal-Srivastava there, can you please share the screenshot of the error too. It will be much more known what the issue was. 

If it doesn't support in Powershell, then you can use Cygwin to support Unix commands in your windows machine. Thank you

**Comment by Hinal-Srivastava** [comment]
Hey!
![image](https://user-images.githubusercontent.com/28009493/94504351-3409c380-0226-11eb-9469-740b2fec785b.png)
I faced the error in cmd. Didn't try PowerShell

**Comment by Aju100** [comment]
> Hey!
> ![image](https://user-images.githubusercontent.com/28009493/94504351-3409c380-0226-11eb-9469-740b2fec785b.png)
> I faced the error in cmd. Didn't try PowerShell

As I mentioned in my initial comment. Please use Cygwin to support unix commands in your windows machine. It will support those commands.

**Comment by Hinal-Srivastava** [comment]
Yes! did that. Thanks

**Comment by Aju100** [comment]
@Hinal-Srivastava  cool let's disclose this issue
