### ISSUE TITLE
docs : Update setup instructions

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#163]
## Description
As a contributor , 
I need the setup instructions upto date for all OS.

1)   .\env\Scripts\activate does not work for CMD as mentioned in instructions 
Soln : Remove entire paragraph and update to just 2 lines as the command is bound to 100% work
 ```
On Windows
For git bash users :  source ./venv/Scripts/activate
 For cmd users : venv\Scripts\activate
```
![image](https://user-images.githubusercontent.com/60894542/94734163-79dd9d80-0386-11eb-8bf5-a4036c031efd.png)

2) To maintain consistency in setup doc all commands in step 6 should be included in code blocks rather than it's current state 

3) Substep 1 and 2 of step 6 should include double quotes (" ") in stead of single quotes . Then only it works .
![image](https://user-images.githubusercontent.com/60894542/94734608-19029500-0387-11eb-87b8-285d1ea59d51.png)

4) The output of  git remote -v  has minor changes update them
 and also add cd bridge-in-tech-backend before adding upstream otherwise a fatal error is received
![image](https://user-images.githubusercontent.com/60894542/94736878-9085f380-038a-11eb-88e9-916610c02964.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by vj-codes** [comment]
@mtreacy002 hey I would like to work on this , can this be a good first issue for me? 👀

**Comment by mtreacy002** [comment]
Thank you @vj-codes for reporting this issue. Yes, definitely this can be the first issue for you. This issue will really help other contributors on Windows machine. I really appreciate your help... 🥰
