### ISSUE TITLE
Auditing the dependencies by fixing/upgrading/removing them

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/bridge-in-tech-backend#166]
**Is your feature request related to a problem? Please describe.**
In the requirements file, there are a lot of dependencies that cause various bugs and conflicts similar to #157 

**Describe the solution you'd like**
We should manually audit the requirements file to keep the required packages only.

**Describe alternatives you've considered**
I would suggest to not use `pip freeze`  command for generating requirements file onwards. Also, this can be added as a check in pull request template and contribution guidelines so that contributors can keep a track of this.

**Comment by devkapilbansal** [comment]
@mtreacy002 I would like to work on this issue

**Comment by mtreacy002** [comment]
Sure. Thanks for opening the issue @devkapilbansal . I'll assign you to this now.

**Comment by devkapilbansal** [comment]
Thanks, will make a pr soon
