### ISSUE TITLE
docs: Add the required changes to BIT development environment setup wiki page

### ISSUE THREAD

**Issue by ashwinijha6** [anitab-org/bridge-in-tech-backend#177]
## Description
As a developer,
I need rectify certain minor errors in the **BIT development environment setup wiki page**,
so that a new user can apply it correctly for the setup.

## Mocks

![command $](https://user-images.githubusercontent.com/45794450/103458003-ebccd680-4d29-11eb-9c28-4ac69091f776.JPG)

![line](https://user-images.githubusercontent.com/45794450/103458068-90e7af00-4d2a-11eb-8034-e682b45a2dc5.JPG)

### Update [Required]
- [ ] add a shell prompt '$' before the command **psql -c "ALTER DATABASE bit_schema SET search_path TO bitschema,public;" -U postgres -d bit_schema**
- [ ] correct the line number to uncomment (102) & comment (100) under TestingConfig in config.py
- [ ] add appropriate screenshot of config.py

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by ashwinijha6** [comment]
@mtreacy002 could u pls assign this issue to me so that I can make the necessary changes

**Comment by ashwinijha6** [comment]
![revised screenshot](https://user-images.githubusercontent.com/45794450/103474554-1ae75480-4dcb-11eb-9555-670ec87ebf35.JPG)

**Comment by ashwinijha6** [comment]
@mtreacy002 just let me know that I need to make changes to the[ wiki page](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup) directly or this [doc](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/ENV_SETUP_INSTRUCTION.md) I see some changes already made by @vj-codes but they don't reflect in the wiki page.
Also I guess a wiki page can be edited only by repository collaborators.

**Comment by mtreacy002** [comment]
@ashwinijha6. To update the BIT development environment setup page, you can update them directly on the file (ENV_SETUP_INSTRUCTION.md under .github folder ) that is being used in the Wiki. Hope this answers your question 😉

**Comment by ashwinijha6** [comment]
> @ashwinijha6. To update the BIT development environment setup page, you can update them directly on the file (ENV_SETUP_INSTRUCTION.md under .github folder ) that is being used in the Wiki. Hope this answers your question 😉

Ok @mtreacy002  I'll do that .
but I don't understand why there is a difference in the wiki page & doc that is (ENV_SETUP_INSTRUCTION.md under .github folder ) like in the 8th step?

**Comment by mtreacy002** [comment]
I just checked and noticed that as well.. 🤔. Perhaps there is a bug in the code that we need to investigate? Another good pick up, @ashwinijha6 . Since you're working on the issue, can you please investigate this and apply the fix?

**Comment by ashwinijha6** [comment]
> I just checked and noticed that as well.. 🤔. Perhaps there is a bug in the code that we need to investigate? Another good pick up, @ashwinijha6 . Since you're working on the issue, can you please investigate this and apply the fix?

Ok I'll surely look into it @mtreacy002

**Comment by ashwinijha6** [comment]
I guess @mtreacy002 certain changes were made by @vj-codes in the pull request #164 which merged to develop branch. But the wiki pages are documented on the master branch & that's the reason the changes are not reflected. 
This could be the reason.

**Comment by mtreacy002** [comment]
@ashwinijha6 ,  can you please post the screen shots here on how are they different from each other (the one on wiki and the one on the file)? Since from my end they both look the same?? I don't know how I saw them differently before, but when I checked again just now the differences aren't showing 🤔

**Comment by ashwinijha6** [comment]
> @ashwinijha6 , can you please post the screen shots here on how are they different from each other (the one on wiki and the one on the file)? Since from my end they both look the same?? I don't know how I saw them differently before, but when I checked again just now the differences aren't showing 🤔

ok let me check

**Comment by ashwinijha6** [comment]
[Wiki page](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup)
3rd step does not contain screenshots
![3rd step wiki](https://user-images.githubusercontent.com/45794450/103516661-e80a9280-4e96-11eb-92e8-83eb76896bc3.JPG)

**Comment by ashwinijha6** [comment]
[ENV_SETUP_INSTRUCTION.md](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/ENV_SETUP_INSTRUCTION.md) also in the sidebar of the wiki page.
3rd step contains screenshots 
![3rd step ENV_SETUP md](https://user-images.githubusercontent.com/45794450/103516848-315ae200-4e97-11eb-9338-5f45694dbdd2.JPG)

**Comment by ashwinijha6** [comment]
Also @mtreacy002 u can find a difference in the 8th step using the above links

**Comment by vj-codes** [comment]
@mtreacy002 @ashwinijha6 from what I've observed right now is that the wiki page does not take the info from .md setup file . 
The wiki revision history is not the same as .md file history so wiki instructions need to be updated separately .
The sidebar links ENV_SETUP_INSTRUCTION.md and thus I would suggest to keep only one setup instructions , preferably the .md file as it can be updated by other contributors later too OR @mtreacy002 needs to manually update it every time a change is made.
What say ?

**Comment by ashwinijha6** [comment]
> @mtreacy002 @ashwinijha6 from what I've observed right now is that the wiki page does not take the info from .md setup file .
> The wiki revision history is not the same as .md file history so wiki instructions need to be updated separately .
> The sidebar links ENV_SETUP_INSTRUCTION.md and thus I would suggest to keep only one setup instructions , preferably the .md file as it can be updated by other contributors later too OR @mtreacy002 needs to manually update it every time a change is made.
> What say ?

Yes, even I noticed that the changes are not updated as per the .md file.

**Comment by mtreacy002** [comment]
> [Wiki page](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup)
> 3rd step does not contain screenshots
> ![3rd step wiki](https://user-images.githubusercontent.com/45794450/103516661-e80a9280-4e96-11eb-92e8-83eb76896bc3.JPG)

@ashwinijha6 , this is interesting. The link you gave me seems to be different than the link I opened when I clicked on the setup instruction from wiki page.

Copy pasting the link address, I found the following:
Link from your post:
https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup

whereas link from wiki page click:
https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/ENV_SETUP_INSTRUCTION.md

![ezgif com-gif-maker (20)](https://user-images.githubusercontent.com/29667122/103822945-2eddcf80-50c5-11eb-82aa-190ea932027f.gif)

Can you please tell me how you get to the wiki link on your post above?

**Comment by mtreacy002** [comment]
> @mtreacy002 @ashwinijha6 from what I've observed right now is that the wiki page does not take the info from .md setup file .
> The wiki revision history is not the same as .md file history so wiki instructions need to be updated separately .
> The sidebar links ENV_SETUP_INSTRUCTION.md and thus I would suggest to keep only one setup instructions , preferably the .md file as it can be updated by other contributors later too OR @mtreacy002 needs to manually update it every time a change is made.
> What say ?

@vj-codes and @ashwinijha6 . Ideally we do want the wiki pages to be in .md files. So I agree, we should stick with the ENV_SETUP_INSTRUCTION.md. I will remove the wiki pages version from wiki.

**Comment by mtreacy002** [comment]
Done

**Comment by ashwinijha6** [comment]
> > @mtreacy002 @ashwinijha6 from what I've observed right now is that the wiki page does not take the info from .md setup file .
> > The wiki revision history is not the same as .md file history so wiki instructions need to be updated separately .
> > The sidebar links ENV_SETUP_INSTRUCTION.md and thus I would suggest to keep only one setup instructions , preferably the .md file as it can be updated by other contributors later too OR @mtreacy002 needs to manually update it every time a change is made.
> > What say ?
> 
> @vj-codes and @ashwinijha6 . Ideally we do want the wiki pages to be in .md files. So I agree, we should stick with the ENV_SETUP_INSTRUCTION.md. I will remove the wiki pages version from wiki.

ok @mtreacy002 now I will make the necessary changes related to my issue
Thanx for the help @mtreacy002 & @vj-codes

**Comment by mtreacy002** [comment]
I'm closing this issue since we've removed the conflicting files (Wiki page) and use the link to ENV_SETUP_INSTRUCTIONS.md instead on the wiki sidebar menu which fix the issue raised here.
