### ISSUE TITLE
The description for Web Client on heroku does not match

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#179]
## Description
As a developer,I need to keep the heroku description updated 
so that all users are clear about the project.

1)Go to https://bridgeintech-bit-heroku-psql.herokuapp.com/
2)Read second last line about the web client 
3)It should be Bridge In Tech and not Mentorship System

## Mocks
![image](https://user-images.githubusercontent.com/60894542/105508006-de37ba80-5cf1-11eb-82ee-4a16ff212e7b.png)

### Update [Required]
- [ ] Project name is updated accordingly 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by vj-codes** [comment]
@mtreacy002 hey once you approve this issue , can it be made available as` first timers only`? Since it's relatively easyy

**Comment by Rahulm2310** [comment]
@vj-codes If approved, I would like to fix this 😊

**Comment by mtreacy002** [comment]
Good call, @vj-codes. Thanks for opening this issue and give it a proper label. @Rahulm2310, definitely. I'll assign you to this now 😉
