### ISSUE TITLE
Doc: Update link to setup instructions on Readme file.

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#180]
**Describe the bug**
The previous **BIT Backend Environment Setup** linked to a wiki page that is not longer exist since now we're using the ENV_SETUP_INSTRUCTION.md under .github folder. Therefore the link inside the Readme file need to be updated to reflect this change.

**To Reproduce**
1. Go to bridge-in-tech-backend repository and click on the link to **BIT Development Environment Setup**

2. See an empty wiki page (not the expected behaviour)
<img width="1048" alt="Screen Shot 2021-01-22 at 11 04 06 am" src="https://user-images.githubusercontent.com/29667122/105428790-4364bf00-5ca4-11eb-9d2b-84b4f67d9e80.png">

3. Now Go to the Wiki page and click on the link to the same page from the side bar

<img width="246" alt="Screen Shot 2021-01-22 at 11 04 33 am" src="https://user-images.githubusercontent.com/29667122/105428483-98540580-5ca3-11eb-88cf-b4b85cb0c5b0.png">

<img width="1038" alt="Screen Shot 2021-01-22 at 11 05 20 am" src="https://user-images.githubusercontent.com/29667122/105428590-c3d6f000-5ca3-11eb-98ac-01688bd221fd.png">

**Expected behavior**
The link on the Readme of repository need to lead to the same page as the wiki side bar does

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Version: Catalina 10.15.7, Safari 14.0.2

**Comment by 0xNilesh** [comment]
I would like to work on this issue.

**Comment by mtreacy002** [comment]
Sure, @VectoTec. You can work on it 😉

**Comment by 0xNilesh** [comment]
Thanks for assigning me 😄.
