### ISSUE TITLE
Use HTTPStatus code values instead of enum representation in Organisations API

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/bridge-in-tech-backend#183]
**Describe the bug**

The values shown on Swagger UI of Users API should be in number format instead of Enum Representations of Status Codes. For example 200 instead of HTTPStatus.OK. 

**To Reproduce**

1. Go to https://bridgeintech-bit-heroku-psql.herokuapp.com/
2. Scroll down to ```Organisations Api```
3. See enum representation.

![image](https://user-images.githubusercontent.com/66299533/105664003-96837f80-5ef9-11eb-8d31-971ac60efc2c.png)

**Expected behavior**
Use of Values of Status Codes instead of Enum Representations in Swagger UI

**Desktop (please complete the following information):**
 - OS: Ubuntu 20+
 - Browser FireFox Web Browser
 - Version --

**Comment by Rahulm2310** [comment]
@Aaishpra If approved, I would like to work on this issue. Thanks

**Comment by Aaishpra** [comment]
@Rahulm2310 you are already assigned to #179 and you can't be assigned to two issues at a time in a repo/project and after getting approved this issue will be a first timer so let this be available for someone new to the project.
Hope it makes sense 😬

**Comment by Rahulm2310** [comment]
Although, I have created a PR for #179 and it is ready to be merged. Still, I completely get your point. 😊

**Comment by urvashi-code1255** [comment]
@Aaishpra Do we have to change these to the status code only? Means Hardcoded values right?
![Capture](https://user-images.githubusercontent.com/63122133/107231617-8665b700-6a46-11eb-9dc4-1839d95c14d0.PNG)

**Comment by nayaldivya** [comment]
Hi @Aaishpra, I would like to work on this issue.

**Comment by Aaishpra** [comment]
> Hi @Aaishpra, I would like to work on this issue. 

Cc: @mtreacy002

**Comment by shades-7** [comment]
@mtreacy002 hey if it's still open I would like to take this issue.

**Comment by mtreacy002** [comment]
@shades-7 , let's see if @nayaldivya still working on this. @nayaldivya, can you please give us an update?

**Comment by mtreacy002** [comment]
@shades-7 , we hear no reply from @nayaldivya . If you are still interested on the issue, I'll assign you to this.

**Comment by mtreacy002** [comment]
@shades-7 . this issue is yours to work on now 😉

**Comment by mtreacy002** [comment]
@shades-7 , can we please get an update on this issue?

**Comment by shades-7** [comment]
@mtreacy002 I am on it, 
please check the values in the table below, are they correct? 
if yes will update soon.

| Current Value      | New Value     | 
| :------------- | :----------: | 
|  HTTPStatus.UNAUTHORIZED | 401   | 
|   HTTPStatus.FORBIDDEN  | 403 | 
|   HTTPStatus.OK |  200 | 
|   HTTPStatus.INTERNAL_SERVER_ERROR | 500 |

**Comment by Aaishpra** [comment]
@shades-7 you just need to add.  `.value` after every `http.status.x` so don't worry much about the table and other things when you will add .value the enum representation of status codes will automatically convert themselves into real number representation.
For refrence take a look at #188 
Btw the table is absolutely correct 👍🏻

**Comment by shades-7** [comment]
@Aaishpra Thanks for the guidance will get into it and let you know the update soon.

**Comment by shades-7** [comment]
Hey, I was setting the project locally can someone help me with the 7th step I don't get what we need to do.
![Screenshot from 2021-03-08 19-07-34](https://user-images.githubusercontent.com/58786336/110328612-91aa0380-8041-11eb-9e7c-498d89b7c3a4.png)

wanted to know **how to create a .env file from the .env.template?**

**Comment by epicadk** [comment]
> wanted to know **how to create a .env file from the .env.template?**

1.) You can open the file in a text editor of your choice 
2.) Set the values of the environment variables
3.) Press `Save as` and name the file `.env`

I hope this helps. 😄 @shades-7

**Comment by shades-7** [comment]
@epicadk sorry for bothering you so much, but can you help me with env values, I don't understand what will go in all these variables:
FLASK_ENVIRONMENT_CONFIG = <local-dev-or-test-or-prod>
SECRET_KEY = <your-secret-key>
SECURITY_PASSWORD_SALT = <your-security-password-salt>
MAIL_DEFAULT_SENDER = <mail-default-sender>
MAIL_SERVER = <mail-server>
APP_MAIL_USERNAME = <app-mail-username>
APP_MAIL_PASSWORD = <app-mail-password>
MOCK_EMAIL = <True-or-False>

**Comment by shades-7** [comment]
> > wanted to know **how to create a .env file from the .env.template?**
> 
> 1.) You can open the file in a text editor of your choice
> 2.) Set the values of the environment variables
> 3.) Press `Save as` and name the file `.env`
> 
> I hope this helps.  @shades-7

Thank you got that

**Comment by epicadk** [comment]
> @epicadk sorry for bothering you so much, but can you help me with env values, I don't understand what will go in all these variables:
> FLASK_ENVIRONMENT_CONFIG =
> SECRET_KEY =
> SECURITY_PASSWORD_SALT =
> MAIL_DEFAULT_SENDER =
> MAIL_SERVER =
> APP_MAIL_USERNAME =
> APP_MAIL_PASSWORD =
> MOCK_EMAIL =

Oh are these missing from the setup instructions? Even I can't seem to find the env variables guide. You can use the one on mentorship since they are pretty much the same. You can find the instructions [here](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md). And please don't hesitate to ask someone from the community will definitely help you out. You could also try asking on zulip where a lot more people would be able to help you out. 😄

**Comment by Aaishpra** [comment]
@shades-7 [this](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Dev.20Env.20Setup/near/223808070) might help you.

**Comment by shades-7** [comment]
@Aaishpra @epicadk Thank you so much :heart: 
you guys were so helpful, I am able to run the system locally :partying_face:

**Comment by mtreacy002** [comment]
> > @epicadk sorry for bothering you so much, but can you help me with env values, I don't understand what will go in all these variables:
> > FLASK_ENVIRONMENT_CONFIG =
> > SECRET_KEY =
> > SECURITY_PASSWORD_SALT =
> > MAIL_DEFAULT_SENDER =
> > MAIL_SERVER =
> > APP_MAIL_USERNAME =
> > APP_MAIL_PASSWORD =
> > MOCK_EMAIL =
> 
> Oh are these missing from the setup instructions? Even I can't seem to find the env variables guide. You can use the one on mentorship since they are pretty much the same. You can find the instructions [here](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md). And please don't hesitate to ask someone from the community will definitely help you out. You could also try asking on zulip where a lot more people would be able to help you out. 😄

@epicadk , the setup instructions has covered these steps [here](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/ENV_SETUP_INSTRUCTION.md#7th-create-the-env-file-using-envtemplate). @shades-7 , can you please give feedback in what way this instruction can be improved so it's clear to the new contributors? Really appreciate your input 😉

**Comment by shades-7** [comment]
> > > @epicadk sorry for bothering you so much, but can you help me with env values, I don't understand what will go in all these variables:
> > > FLASK_ENVIRONMENT_CONFIG =
> > > SECRET_KEY =
> > > SECURITY_PASSWORD_SALT =
> > > MAIL_DEFAULT_SENDER =
> > > MAIL_SERVER =
> > > APP_MAIL_USERNAME =
> > > APP_MAIL_PASSWORD =
> > > MOCK_EMAIL =
> > 
> > 

> @epicadk , the setup instructions has covered these steps [here](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/ENV_SETUP_INSTRUCTION.md#7th-create-the-env-file-using-envtemplate). @shades-7 , can you please give feedback in what way this instruction can be improved so it's clear to the new contributors? Really appreciate your input

@mtreacy002 I believe things will be much easier if we can change the link of **environmental variable_tb** highlighted in the picture below with [this](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/docs/ENVIRONMENT_VARIABLES.md) link 


![Screenshot from 2021-03-09 11-07-37](https://user-images.githubusercontent.com/58786336/110423773-b1840a80-80c7-11eb-800e-7a7a6d0a9f46.png)

**Comment by shades-7** [comment]
@mtreacy002 if you think it will be a good change, then may I open this as an issue?

**Comment by epicadk** [comment]
> @mtreacy002 if you think it will be a good change, then may I open this as an issue?

I agree. You can open the issue. 😁 Also you don't need to ask , anyone can open an issue just make sure you are following the contributing guidelines.

**Comment by mtreacy002** [comment]
@shades-7 , are you able to setup and run successfully? Can you please give us an update on this issue? Will you be able to send a PR soon?

**Comment by shades-7** [comment]
@mtreacy002 I will send the PR by today

**Comment by HeroicHitesh** [comment]
@shades-7 can we have an update on the progress regarding this issue?

**Comment by shades-7** [comment]
@mtreacy002 hello I tried but I am unable to fix it. it would be better to assign someone else

**Comment by epicadk** [comment]
> @mtreacy002 hello I tried but I am unable to fix it. it would be better to assign someone else

Would you like a hint instead?

**Comment by shades-7** [comment]
> > @mtreacy002 hello I tried but I am unable to fix it. it would be better to assign someone else
> 
> Would you like a hint instead?

Yes, that will be great

**Comment by epicadk** [comment]
@shades-7 Have you located the file where you need to make the change?

**Comment by shades-7** [comment]
@epicadk No

**Comment by epicadk** [comment]
You need to make changes to [this file.](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/app/api/resources/organizations.py#L1)

**Comment by shades-7** [comment]
@epicadk Thank you for your guidance i have created a PR please review it
