### ISSUE TITLE
Setup black formatter and it's github action

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#184]
**Is your feature request related to a problem? Please describe.**
As a developer, I need to have good, structured, readable code to be able to read through it painlessly and effortlessly.

**Describe the solution you'd like**
The idea is to run Black through a single pass, and then integrate the [official GitHub action](https://github.com/psf/black#github-actions) so that we make it a habit for every developer to run black before committing their code.

**Comment by Rahulm2310** [comment]
@vj-codes Hey, I would like to work on this.

**Comment by mtreacy002** [comment]
@vj-codes , perhaps we should separate this issue into 2? One for Black formatter and the other is for Github action?

**Comment by vj-codes** [comment]
@mtreacy002 ahh no this is for setting up black in the repo so it can be used locally , and the black's gh actions to check code format while a PR is created.

**Comment by mtreacy002** [comment]
I see. Does that mean we need to move Travis first to GitHub action?

**Comment by Rahulm2310** [comment]
@vj-codes Can't we integrate Black with Travis CI ?

**Comment by vj-codes** [comment]
@mtreacy002 yes moving away from travis to github actions sounds fairly efficient .
@Rahulm2310 since we are going to move to gh actions, integrating with travis is not a good choice it'll be just double work  if we do so.

**Comment by mtreacy002** [comment]
Ok then, @vj-codes. Would you like to work on this or can @Rahulm2310 pick it up?

**Comment by vj-codes** [comment]
@mtreacy002 I would like to !

**Comment by mtreacy002** [comment]
Ok, I'll assign you to this @vj-codes 😉

**Comment by vj-codes** [comment]
Update- implemented black, and gh action for it as well , shall I create a PR or wait until gh action for running tests same as travis is done ? @mtreacy002

**Comment by mtreacy002** [comment]
Have you tried running the test on your own fork repo, @vj-codes ? II'm pretty sure we can try it there first, right @isabelcosta?
