### ISSUE TITLE
Feature of Deploy from Github Actions

### ISSUE THREAD

**Issue by aditmehta9** [anitab-org/bridge-in-tech-backend#190]
**Is your feature request related to a problem? Please describe.**
Creation of deploy.yml file from Github Actions

**Describe the solution you'd like**
Creation of deploy.yml file in .github/workflow category

**Additional context**
![image](https://user-images.githubusercontent.com/35133994/107322681-ef8f0e00-6aca-11eb-8de6-da8c4705e339.png)

**Comment by aditmehta9** [comment]
@mtreacy002 can this issue can be assigned to me as I haven't contributed to this repo and it is also the task of OS Ambassador more work needed section?

**Comment by mtreacy002** [comment]
Sure, @aditmehta9 . I'll assign you to this. 😉

**Comment by aditmehta9** [comment]
> 
> 
> Sure, @aditmehta9 . I'll assign you to this. 😉

Thanks

**Comment by mtreacy002** [comment]
This issue is closed due to it is not possible to deploy backend to static gh-pages (refer to this [MS backend pr](https://github.com/anitab-org/mentorship-backend/pull/995) discussion).
