### ISSUE TITLE
Wrong information in pull request template

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#193]
**Describe the bug**
In the pull request template , under checklist read last point -
`I have written Kotlin Docs whenever is applicable`
Bridge in tech does not use kotlin docs in either frontend or backend so that point should be removed.

**To Reproduce**
1. Go to 'PULL_REQUEST_TEMPLATE.md'
2. Scroll down to 'Checklist>>>Last point'
3. See error

**Expected behavior**
It shouldn't exist.

**Comment by vj-codes** [comment]
@mtreacy002 I believe this might be due to copy pasting the template from ms-android repo 👀 
It can be a good first issue for contributors , what say?

**Comment by decon-harsh** [comment]
@vj-codes I agree , I got confused too , haha

**Comment by mtreacy002** [comment]
Great catch, @vj-codes . I agree, it's a good first-timer issue 😉.

**Comment by Debanitrkl** [comment]
@mtreacy002 @vj-codes could I take up this issue?

**Comment by vj-codes** [comment]
Assigning you @Debanitrkl 
Happy documenting!
