### ISSUE TITLE
Feat: Migrating documentation from wiki to docusaurus

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-backend#198]
**Is your feature request related to a problem? Please describe.**
Current documentation is fine but with `docusaurus` , the documentation becomes more readable and maintainable.

**Describe the solution you'd like**
Moving the project's documentation to [docusaurus](https://v2.docusaurus.io).

**Additional context**
Mentorship System and Open source programs projects are moving documentation to docusaurus.

**Comment by Rahulm2310** [comment]
@mtreacy002 Please share your thoughts 🙂. If you approve, I would like to take this up.

**Comment by mtreacy002** [comment]
Sure, @Rahulm2310 . I'll assign you to this now.

**Comment by Rahulm2310** [comment]
@mtreacy002 I have migrated the documentation from wiki to docusaurus. Here's a link to hosted site https://bit-backend-docs.surge.sh/. Please give your suggestions. If all good, I can create a PR.🙂

**Comment by mtreacy002** [comment]
@Rahulm2310 , can you please explain to me what will happen with Wiki once we adopted this in our project repo? will the wiki page still be there? And where will we see the link to this docusaurus (README file or elsewhere? Thanks

**Comment by mtreacy002** [comment]
@Rahulm2310 . You can remove the `How to contribute` section because I want the contributor to go to the `Getting Started` page to know more about how to make contribution. This is because if we keep them both, the contributor can easily overlook the `Getting Started` page which actually has important guidelines for them on how to contribute to the project (like the GitHub workflow). Plus, the `Commit message style guide` is accessible inside the `Getting Started` page.
<img width="615" alt="Screen Shot 2021-02-21 at 1 16 19 pm" src="https://user-images.githubusercontent.com/29667122/108613568-57d4dc80-7447-11eb-9fb1-112257ed6a07.png">

**Comment by mtreacy002** [comment]
Also, I've just added a new section on wiki for BIT redesign related files. Can you please add this on the docusaurus, please? Thanks
<img width="243" alt="Screen Shot 2021-02-21 at 1 30 00 pm" src="https://user-images.githubusercontent.com/29667122/108613770-1d6c3f00-7449-11eb-9427-958984d6f7b6.png">

**Comment by Rahulm2310** [comment]
> @Rahulm2310 , can you please explain to me what will happen with Wiki once we adopted this in our project repo? will the wiki page still be there? And where will we see the link to this docusaurus (README file or elsewhere? Thanks

@mtreacy002  Nothing will happen to the wiki. It will remain intact. We will just have a more appealing and readable documentation. We can add a `Documentation` section in the readme and provide there a link to the docusaurus website. Or if you have a suggestion, please put it forward.

>@Rahulm2310 . You can remove the How to contribute section because I want the contributor to go to the Getting Started page to know more about how to make contribution. This is because if we keep them both, the contributor can easily overlook the Getting Started page which actually has important guidelines for them on how to contribute to the project (like the GitHub workflow). Plus, the Commit message style guide is accessible inside the Getting Started page.

Sure, I will apply all the suggested changes. Thanks 🙂

**Comment by Rahulm2310** [comment]
@mtreacy002 Applied suggested changes. Please take a look https://bit-backend-docs.surge.sh/

**Comment by mtreacy002** [comment]
@Rahulm2310 , thanks for your explanation. Yep, I think we can add the link to docusaurus in Readme 👍. Can you please add that to your changes? Thanks.

**Comment by mtreacy002** [comment]
@Rahulm2310 , can you please add the new changes for meeting minutes section I added on wiki?
<img width="249" alt="Screen Shot 2021-02-22 at 9 15 27 am" src="https://user-images.githubusercontent.com/29667122/108640594-bb661500-74ee-11eb-9bde-c84d4ab12c21.png">

**Comment by Rahulm2310** [comment]
@mtreacy002 Applied suggested changes and submitted a PR. Please review it 🙂
