### ISSUE TITLE
Remove .github/ISSUE_TEMPLATE folder 

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#201]
### Description
As a org admin / maintainer,
I need to maintain 1 version of issue templates used in the organization,
so that I can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Acceptance Criteria
**Update [Required]**

- [ ]  Delete .github/ISSUE_TEMPLATE

**Definition of Done**

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

**Estimation**
0.5 hours

**Comment by sahil9001** [comment]
Can I take this up?

**Comment by mtreacy002** [comment]
Sure @sahil9001 . I'm assigning you now.
