### ISSUE TITLE
Bug: Token expiry no longer returned by MS backend

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#203]
**Describe the bug**
Token expiry has been removed from the MS backend response when user login. This causes server crash since the BIT logic still checks for this token expiry when validating token. 

**To Reproduce**
1. Update your version of ms-backend-server by pulling the latest update from https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server.
It should include commit #1021 as the latest commit from MS backend
<img width="1160" alt="Screen Shot 2021-03-03 at 4 44 26 pm" src="https://user-images.githubusercontent.com/29667122/109758561-e0b9f800-7c3f-11eb-8cb2-b6f22ca1dd07.png">
 
2. Run ms-backend-server and bit backend server. 
3. Try to login from BIT Swagger UI, and see errror (see screenshot 1)
4. Go to terminal and see error (see screenshot 2)

**Expected behavior**
Once the token expiry check is removed from valid_token logic, user should be able to login. (see screenshot 4)

**Screenshots**
Screenshot 1 - Swagger UI error
<img width="983" alt="Screen Shot 2021-03-03 at 4 48 24 pm" src="https://user-images.githubusercontent.com/29667122/109759281-dc420f00-7c40-11eb-8c81-6a62ec0473d0.png">

Screenshot 2 - Terminal error
<img width="706" alt="Screen Shot 2021-03-03 at 4 53 46 pm" src="https://user-images.githubusercontent.com/29667122/109759386-07c4f980-7c41-11eb-9501-e8792a109699.png">

Screenshot 3 - The cause of error
<img width="576" alt="Screen Shot 2021-03-03 at 4 55 06 pm" src="https://user-images.githubusercontent.com/29667122/109759557-49ee3b00-7c41-11eb-90d8-7ca7c09b5a19.png">

Screenshot 4 - Successful login once the token expiry check is removed
<img width="738" alt="Screen Shot 2021-03-03 at 5 07 49 pm" src="https://user-images.githubusercontent.com/29667122/109760566-fe3c9100-7c42-11eb-8c53-0a224d442494.png">

**Desktop:**
 - OS: MacOS 
 - Browser: Chrome
 - Version: MacOS: Catalina v.10.15.7; Chrome: v88.0.4324.192 

**Additional context**
NA

**Comment by sahil9001** [comment]
Hey can I take this up?

**Comment by mtreacy002** [comment]
@sahil9001. This issue is labelled `First timers only` so let's give those who never contributed before to claim this issue. You've made contribution through #201 😉

**Comment by sahil9001** [comment]
> @sahil9001. This issue is labelled `First timers only` so let's give those who never contributed before to claim this issue. You've made contribution through #201 😉

Okay😂👍

**Comment by 17sushmita** [comment]
Can I take this issue?

**Comment by mtreacy002** [comment]
Sure, @17sushmita . I'll assign this to you now. Thank you for picking up the issue 😉

**Comment by b-thebest** [comment]
Can I take up this issue, token expiry has been removed from mentorship backend. I am first timer to this repo.

**Comment by mtreacy002** [comment]
@b-thebest , thanks for showing interest on this issue. @17sushmita has been assigned to this as she claimed the issue first 😉.

**Comment by b-thebest** [comment]
@mtreacy002 No problem, In any case if PR not made I can work. expiry time is no longer returned by MS backend by the way.
