### ISSUE TITLE
Bug: Creation of program with non-unique name throws an unhandled error

### ISSUE THREAD

**Issue by NenadPantelic** [anitab-org/bridge-in-tech-backend#205]
### Describe the bug
Currently, if we add an organization with the name that was used before (non-unique name), we got an unhandled server error. 
### To Reproduce
1. Go to Swagger UI or client app like Postman/Insomnia
2. Send the  POST request to `/organizations/{organization_id}/programs/program`
3. An unhandled error is returned

### Expected behavior
We should not 500 as a response code with an unprocessed message. We should get handled exception error with the message that the program name is already used.

### Screenshots
![image](https://user-images.githubusercontent.com/16724101/110143387-7dfb6480-7dd7-11eb-9b78-02251d0015ee.png)

### Desktop (please complete the following information):
 - OS: elementary OS 5.1.7 Hera (built on Ubuntu)
 - Browser: Google Chrome 
 - Version: 88.0.4324.182

### Additional context
N/A

**Comment by NenadPantelic** [comment]
@mtreacy002 Can you please, label it and assign me?

**Comment by NenadPantelic** [comment]
PR #189 solves this.

**Comment by mtreacy002** [comment]
done, @NenadPantelic . Will you also like to work on the other issue #110 or should I unassign you from there?

**Comment by mtreacy002** [comment]
@NenadPantelic , please remove the `Smartphone` section from issue description but be specific on the `Desktop` section of your machine env.

**Comment by mtreacy002** [comment]
> PR #189 solves this.

Please link that PR to this issue.

**Comment by NenadPantelic** [comment]
> done, @NenadPantelic . Will you also like to work on the other issue #110 or should I unassign you from there?

I can handle that too, first to get #189 merged.
