### ISSUE TITLE
Change the link for setting environmental variables

### ISSUE THREAD

**Issue by shades-7** [anitab-org/bridge-in-tech-backend#210]
### Describe the bug
The present link for setting the environment variable is not clear enough.

### To Reproduce
1. Go to 'README.md'
2. Click on 'BIT Development Environment Setup Instruction '
3. Scroll down to '7th, Create the .env file using .env.template'
4. See error by clicking on 'environment variables - tba:'

### Expected behavior
The link should be replaced with [this](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/docs/ENVIRONMENT_VARIABLES.md)

### Screenshots
![Screenshot from 2021-03-09 11-07-37](https://user-images.githubusercontent.com/58786336/110426057-69ff7d80-80cb-11eb-8c56-85b4ceda0371.png)

### Desktop (please complete the following information):
 - OS: [Ubuntu 18.04]
 - Browser [chrome]

**Comment by shades-7** [comment]
@epicadk can I fix this as I am aware of this issue

**Comment by epicadk** [comment]
> @epicadk can I fix this as I am aware of this issue

You have already opened a pull request before. This is for first timers only sorry. You can work on other issues marked `Status: Available`

**Comment by HeroicHitesh** [comment]
@epicadk @mtreacy002 I would like to work on this

**Comment by mtreacy002** [comment]
Sure, @HeroicHitesh . I'll assign you to this.
