### ISSUE TITLE
Feat: Add GET endpoint /users/{userId}/personal-background to fetch personal background from userId

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-backend#216]
### Is your feature request related to a problem? Please describe.
Although we have endpoint /personal-background for a to fetch personal background details of current user (using access_token). We don't have endpoint for a user (org representative) requesting personal background of other user.

### Describe the solution you'd like
There should be a GET endpoint `/users/{userId}/personal-background` for fetching a user's personal background details from userId.

### Additional context
Refer to the discussion [here](https://github.com/anitab-org/bridge-in-tech-web/issues/155).

**Comment by mtreacy002** [comment]
Thank you for raising this issue, @Rahulm2310 . Let me know which one of #215 / #216 you want to work on. I'll assign you to what you choose and make the other available.

**Comment by harsh7in** [comment]
@mtreacy002 can i work on this?

**Comment by mtreacy002** [comment]
Sure, @harsh-9in , I'll assign you on this. @Rahulm2310 , do you want to pick the other one or should I make it available?

**Comment by harsh7in** [comment]
Thanks, @mtreacy002, I am working on this issue.

**Comment by Rahulm2310** [comment]
@harsh-9in Can you please share your progress on this ?

**Comment by devkapilbansal** [comment]
Unassigning @harsh-9in due to lack of response.

**Comment by jalajcodes** [comment]
Making it available for OSH.

**Comment by meganbader** [comment]
Can I work on this issue?

**Comment by epicadk** [comment]
> Can I work on this issue?

Do you want to work on this for osh? If yes please make sure you have setup the app first

**Comment by meganbader** [comment]
Should we only get the user's info if it is public? or does that not matter?

**Comment by jalajcodes** [comment]
> Should we only get the user's info if it is public? or does that not matter?

Getting public info makes more sense, although I am not sure.. cc @mtreacy002

**Comment by mtreacy002** [comment]
You're correct, @meganbader , we only can return user info if the user opted to have their personal info shared publicly. So if it's not, then the organization representative or other users shouldn't be able to see this. There are certain scenarios that the system can return any user info (like when we want to show analysis of users in mentoring programs based on personal background  categories), but the viewers of this data analysis cannot see the details of which user falls into the specific category. Hope this makes sense 😉.
