### ISSUE TITLE
Integrate Black checks

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/bridge-in-tech-backend#218]
### Is your feature request related to a problem? Please describe.
It is necessary for every project to follow some guidelines about how the code should be written, maintained and all. But this misses guidelines related to code quality.

### Describe the solution you'd like
* Format whole code using black
* Add workflow to ensure code is formatted before it is merged to main codebase.

### Additional context
Black formatter is included in [mentorship-backend](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/workflows/black.yml) and can give an idea on how to approach the problem

### Estimated Time
2 hours of work

**Comment by devkapilbansal** [comment]
@mtreacy002 can you please create a label for `Open Source Hack` and label this issue for OSH

**Comment by epicadk** [comment]
#184 duplicate

**Comment by devkapilbansal** [comment]
:grimacing: I didn't noticed it. Thanks @epicadk
