### ISSUE TITLE
Bug: Incorrect edit page link on docusaurus website

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-backend#219]
### Describe the bug
On clicking `Edit this page` button on the docusaurus website, it goes to incorrect link showing `Not Found`. 

### To Reproduce
1. Go to https://bit-backend-docs.surge.sh/docs/
2. Scroll to bottom
3. Click `Edit this page` button

### Expected behavior
It should be linked to correct page on the github repo.
There is a `editUrl` property on the docusaurus config [file](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/docs/docusaurus.config.js) which needs to be corrected. Ideally, the value of `editUrl` should be `https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/docs`

### Screenshots
![bit-backend-edit](https://user-images.githubusercontent.com/54268438/111525086-32579c00-8783-11eb-9337-b844721f0ee4.gif)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

### Additional context
Docusaurus website is hosted here https://bit-backend-docs.surge.sh/

**Comment by prachinandi** [comment]
@Rahulm2310  sir can u assign me this issue , I would like to work on  it.

**Comment by mtreacy002** [comment]
@prachi237 , sure, we will assign you on 1st April when `Open Source Hack` starts 😉 (as per zulip instruction [here](https://anitab-org.zulipchat.com/#narrow/stream/213491-announcements/topic/Open.20Source.20Hack/near/230741560) on OSH). Make sure you setup the environment beforehand so you're ready to go as soon as OSH starts 😉.
cc @Rahulm2310

**Comment by Rahulm2310** [comment]
Also, no need for 'sir' @prachi237 ☺️

**Comment by Aayush-hub** [comment]
@Rahulm2310 @mtreacy002 Can I look into it??

**Comment by epicadk** [comment]
> @Rahulm2310 @mtreacy002 Can I look into it??

Just to confirm is this your first contribution to this repo?

**Comment by Aayush-hub** [comment]
> > @Rahulm2310 @mtreacy002 Can I look into it??
> 
> Just to confirm is this your first contribution to this repo?

@epicadk Yess!

**Comment by Rahulm2310** [comment]
Yours @Aayush-hub . Happy Documenting 😊
