### ISSUE TITLE
Docs: Add badges to docusaurus home.md file

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-backend#224]
### Is your feature request related to a problem? Please describe.

Add badges to docusaurus home.md file.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/54268438/112215300-3b92ae00-8c46-11eb-85aa-c581ef46e667.png)

### Additional context

[shields.io](https://shields.io/) can be used for generating the badges.

**Comment by naveen8801** [comment]
@Amulya-coder  , Please assign it to me :-)

**Comment by Amulya-coder** [comment]
@Rahulm2310 can you please change the title and description of the issue as discussed [here](https://github.com/anitab-org/bridge-in-tech-web/issues/201)

**Comment by naveen8801** [comment]
@Amulya-coder  , @Rahulm2310  , i have made a PR , please review :-)
