### ISSUE TITLE
docs: Add link to Bridge-In-Tech (frontend)

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/bridge-in-tech-backend#225]
### Is your feature request related to a problem? Please describe.

Currently in the readme there is no link to Bridge-in-tech frontend.

### Describe the solution you'd like

Add link to <b>bridge-in-tech-web</b> here:-

![image](https://user-images.githubusercontent.com/66437295/112334047-20c14780-8ce1-11eb-8bdf-89f8e6b5b2ef.png)

### Additional context

None

**Comment by Aryamanz29** [comment]
I would like to work on this issue @Amulya-coder

**Comment by epicadk** [comment]
> I would like to work on this issue @Amulya-coder

Assigning you happy documenting
