### ISSUE TITLE
Docs: Add link to zulip stream in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-backend#229]
### Describe the bug

The link to project's zulip stream is missing in CONTRIBUTING.md. 

### To Reproduce
1. Go to [contributing.md](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/CONTRIBUTING.md)
2. See error

### Expected behavior

Add link to zulip stream in CONTRIBUTING.md

### Screenshots

![bit-cont](https://user-images.githubusercontent.com/54268438/112668901-088a2d80-8e85-11eb-9f5a-d248f945b617.JPG)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by epicadk** [comment]
Wouldn't classify this as a bug.

**Comment by Aryamanz29** [comment]
May i work on this issue?

**Comment by Aryamanz29** [comment]
May I work on this issue? @Rahulm2310

**Comment by jalajcodes** [comment]
@Aryamanz29 This issue is reserved for [Open Source Hack](https://anitab-org.github.io/events/open-source-hack/) program. You can claim it on or after 1st april.

**Comment by Aryamanz29** [comment]
> @Aryamanz29 This issue is reserved for `Open Source Hack` program. You can claim it on or after 1st april.

Ok @jalajcodes

**Comment by y-martinez** [comment]
Hi! @Rahulm2310  or @jalajcodes may I work on this issue? I already made the change I am waiting to made the PR :smile:

**Comment by Rahulm2310** [comment]
@y-martinez next time please request a maintainer to assign you before working on the fix. Go ahead for now 👍
