### ISSUE TITLE
[docs] Migrate docusaurus deployment from surge to gh-pages

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/bridge-in-tech-backend#234]
### Is your feature request related to a problem? Please describe.
It will be better to have the docs on the github-pages.

### Describe the solution you'd like
Deploy the docs on gh-pages.
Take reference from this: anitab-org/mentorship-backend@4cc78ae

Time Required: 1 hour.

**Comment by mtreacy002** [comment]
Making this issue available for all contributors now, not just `First-timers`

**Comment by vj-codes** [comment]
I would like to work on this :)
