### ISSUE TITLE
Research : Assess security concerns in the app

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-backend#240]
### Is your feature request related to a problem? Please describe.

App might have security flaws or loopholes that needs atmost attention. 

### Describe the solution you'd like

Research about security concerns in the app (discuss potential issues, their solutions with proper arguments to support your solution)

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by epicadk** [comment]
I understand your point but the issue seems kinda vague can you be more specific?

**Comment by stableapple** [comment]
Can I work on this?

**Comment by mtreacy002** [comment]
@stableapple , could you please share how you're planning to approach this issue, just so @Rahulm2310 can confirm that it matches to what the pr wants to address 😉

**Comment by stableapple** [comment]
Actually, I don't have much idea about this. I ran Bandit in the app directory and there were some vulnerabilities regarding outdated libraries and hardcoded values in the code. I am planning to address them. It would be great if I can get some help with this. :)

**Comment by Rahulm2310** [comment]
@stableapple good way to start. As this is a research issue, it is open ended. It can be broken authentication, dependency management or anything which might cause a security gap.

**Comment by stableapple** [comment]
Thanks for the suggestion. I'll raise a PR soon. :)

**Comment by stableapple** [comment]
Google doc for the research.
[Google doc](https://docs.google.com/document/d/1y1Q96fnIQcBWFQnCqbL3ijxGly7NdRoX1MPHaGFuvvo/edit?usp=sharing)

**Comment by mtreacy002** [comment]
Thank you, @stableapple . Can you please share the `editable` link of the file (from the screenshot below you can see `Request edit access` on the top right which means the doc is not accessible to others). This is so other contributors can give their feedback and engage on the discussion with you on this topic. Once you've done this, I will add this to BIT backend Wiki sidebar then close this issue 😉 

<img width="1637" alt="Screen Shot 2021-04-30 at 7 21 27 am" src="https://user-images.githubusercontent.com/29667122/116620298-fb30f900-a984-11eb-925a-b3d7fb2b794b.png">

**Comment by stableapple** [comment]
Done @mtreacy002

**Comment by Rahulm2310** [comment]
Looks good. Thanks @stableapple :tada:

**Comment by mtreacy002** [comment]
Thank you @stableapple for your contribution 🎉 🎉 🎉 . Approving this for OSH.

**Comment by mtreacy002** [comment]
The document is now added to the wiki page sidebar
<img width="1237" alt="Screen Shot 2021-05-01 at 6 34 10 am" src="https://user-images.githubusercontent.com/29667122/116751480-6cd17b80-aa47-11eb-924c-207f81600549.png">
