### ISSUE TITLE
Task: Set up local environment

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#244]
## Description
As a contributor
I need to set up local environment for bridge-in-tech-backend and send screenshots,
so that I can provide proof of the same.

## Mocks
NA

### Update [Required]
- [ ] Set up local environment (this means both BIT and MS version for BIT backends must run successfully)
- [ ] Provide a screenshot of a successful response when a user login on Swagger UI (if you haven't done this, you have to register a user first). The screenshot should look similar to the one below:
<img width="1342" alt="Screen Shot 2021-03-30 at 8 50 49 am" src="https://user-images.githubusercontent.com/29667122/112904760-28477d00-9135-11eb-8488-78be9e315c0b.png">

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Additional note**

**1. This is a compulsory task that must be completed before contributors can claim other Open Source Hack issues.
2. The PR that is sibmitted for this task will counted towards the `Documentation/Training` category of Open Source Hack.**. To do this you can create a new branch called `setup` and add an end of line comment inside the run.py (e.g. //Compulsory task - Setup environment) so git pick up a change in the code base. Then once you submit the PR, inside that PR description you can add the screenshot under the "How this has been tested").

**Comment by Aaishpra** [comment]
I addeed the documentation label @mtreacy002.

**Comment by mtreacy002** [comment]
> I addeed the documentation label @mtreacy002.

Thank you, @Aaishpra 😉

**Comment by Rahulm2310** [comment]
@mtreacy002 Please add this note here as well.
#### NOTE: This issue is available for everyone. Please post your screenshots in the comments below.

**Comment by devkapilbansal** [comment]
P.S. - You all are free to create a PR from branch named setup and send your screenshots there. That PR will also be counted for `Documentation` one

**Comment by shades-7** [comment]
Hey, i have submitted the PR can I claim issues now? @devkapilbansal

**Comment by devkapilbansal** [comment]
Sure @shades-7

**Comment by mtreacy002** [comment]
Closing this issue since Open Source Hack has ended.
