### ISSUE TITLE
Improvement: Add typehints to Programs module

### ISSUE THREAD

**Issue by jalajcodes** [anitab-org/bridge-in-tech-backend#247]
## Description

> Type hinting is a formal solution to statically indicate the type of a value within your Python code.

As a developer,
I need to add typehints to my code
to build and maintain a cleaner architecture and catch certain errors along the way.

## Mocks
https://github.com/anitab-org/bridge-in-tech-backend/blob/68d8ff9a8640cef1d3e53b2b0dd9b80e3d750fd7/app/api/dao/organization.py#L179-L182
Here's how to add typehints in above function.
```python
def get_organization(user_id: int, user_name: str):
    representative_additional_info = UserExtensionModel.find_by_user_id(user_id)
    ...
    ...
```
## Resources
Typehints cheatsheet - [Click Here](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)

### Update [Required]
- [ ] Added correct typehints in the files related to Programs module.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Anmollenka** [comment]
I would like to work on this issue.

**Comment by vj-codes** [comment]
@Anmollenka please choose one among this , #242 and #238

**Comment by Anmollenka** [comment]
> @Anmollenka please choose one among this , #242 and #238

Is this issue not open?

**Comment by vj-codes** [comment]
@Anmollenka it is open but you can work only on one issue at once

**Comment by Anmollenka** [comment]
> @Anmollenka it is open but you can work only on one issue at once

Anything is fine.Will go for this first.

**Comment by vj-codes** [comment]
Assigning you @Anmollenka 
Happy coding!
