### ISSUE TITLE
Research : Ideas for how to add members to an organization

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-backend#249]
### Is your feature request related to a problem? Please describe.

We need to think about ideas on how should a member be added to an organization, giving them distinguishing roles (admin/mentor) with api structures for creation, send request, rejection, cancellation with proper gists and model structures. 

### Describe the solution you'd like

Research on it and then create a document describing your idea incorporating all the above asked functionalities. Post the link to the document below in comments.

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by decon-harsh** [comment]
Same as #194
