### ISSUE TITLE
Improve Github actions

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#266]
### Is your feature request related to a problem? Please describe.
Currently we have two separate workflows for lint and build/tests

### Describe the solution you'd like
Have them in the same workflow. Run the lint check before the tests.

**Comment by vj-codes** [comment]
@mtreacy002 hey this was recently done on mentorship-backend , I would like to work on this

**Comment by epicadk** [comment]
> @mtreacy002 hey this was recently done on mentorship-backend , I would like to work on this

Assigning you. Good luck.

**Comment by devkapilbansal** [comment]
@vj-codes please make changes to the tests too that we discussed. Currently they run more than once

**Comment by vj-codes** [comment]
@devkapilbansal yeah sure the ones done on ms-backend right?
