### ISSUE TITLE
Dev: Move Docusaurus from surge to gh-pages

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#272]
## Description
As a contributor,
I need to move BIT backend documentation `docusaurus` from surge to gh-pages, 
so that I can make sure everyone can see the doc on https://anitab-org.github.io/bridge-in-tech-backend

### Update [Required]
- [ ] BIT backend docusaurus should be available on https://anitab-org.github.io/bridge-in-tech-backend

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hr

**Additional Note**
Please refer to MS backend pr [#841](https://github.com/anitab-org/mentorship-backend/pull/841) to learn how this was done there.

**Comment by vj-codes** [comment]
@mtreacy002 can I work on this after OSH is done if no claims it ?

**Comment by mtreacy002** [comment]
Sure, @vj-codes . Please remind me again on the 1 May (post OSH) if no one claim this 😉 .

**Comment by mtreacy002** [comment]
Closing this issue as this is a duplication of issue #234. Sorry for the err. @vj-codes , you can claim the issue #234 instead. I'll remove the `First-timers Only` label as the task had been opened for a while and perhaps need to be done asap to match progress of other Anita.Org projects 😉 .
