### ISSUE TITLE
Docs :  Add setup tutorial to `.github/ENV_SETUP_INSTRUCTION.md`

### ISSUE THREAD

**Issue by Aryamanz29** [anitab-org/bridge-in-tech-backend#277]
### Description

- I want to add an environment setup video link to `ENV_SETUP_INSTRUCTION.md`
- This video tutorial helps new contributors if they got stuck while setting up a dev environment.

**Comment by epicadk** [comment]
Status on hold as this need to be approved by @isabelcosta or @mtreacy002

**Comment by vj-codes** [comment]
@epicadk check [this message from zulip ](https://anitab-org.zulipchat.com/#narrow/stream/223068-celebrate/topic/Highlight.20community.20members!/near/237221609) removing on hold label
