### ISSUE TITLE
Make project beginner friendly

### ISSUE THREAD

**Issue by manthanguptaa** [anitab-org/bridge-in-tech-backend#281]
### Is your feature request related to a problem? Please describe.
So, when I was jumping around the code I was overwhelmed with where exactly is what. It took me some time to figure out what folder contains what and this could be overwhelming for a lot of developers if they are jumping right into it because there is no way around it other than getting your hands dirty.

### Describe the solution you'd like
I propose a solution to add a section in the documentation where the project structure is explained with easy one-liners to understand what exactly that folder/file contains. You can click [here](https://github.com/Manthan109/XMeme) to see the project structure heading example of how it would look.

**Comment by epicadk** [comment]
Thankyou for this issue. We are working towards integrating the bridge in tech backend and the mentorship system backend. This should make the project easier to setup.

**Comment by vj-codes** [comment]
@Manthan109 hey you can read [this blog post](https://medium.com/anitab-org-open-source/bridgeintech-by-anitab-org-85745853865d) or [this google doc](https://docs.google.com/document/d/1uCDCWs8Xyo-3EaUnrLOs48mefXJIN235b1aAswA-s-Y/edit) to know more about the project:)
Also the issues labelled as first-timers only here are a great start 🚀

**Comment by mtreacy002** [comment]
@Manthan109 , if you're proposing to add the file/folder structure to README as per your [example](https://github.com/Manthan109/XMeme), IMO it will be unnecessary since contributors can see them on the repo (above README). Perhaps you can add something like [this diagram](https://github.com/anitab-org/mentorship-backend/issues/530) but a much simpler version. Although, as @epicadk mentioned, when we fully integrate BIT backend to MS backend, the diagram will no longer be needed, so this temporary addition will be short lived.

**Comment by isabelcosta** [comment]
I think we could still have a simple structure of the folder, not too deep, just high-level (2 levels max) folder structure.
I am looking at @Manthan109 suggestion https://github.com/Manthan109/XMeme#folder-structure, so nothing too big, but that gives an idea of the structure of the app (e.g.: where marshmallow schemas as located, and where db models are).
I also think the diagram https://github.com/anitab-org/mentorship-backend/issues/530 can be a little hard to read 🤔 I would say we can try it out on mentorship backend, however on docusaurus sections 🤔 

something like this, without mentioning the files (i.e., that are not frequently changed such as `*_extension.py` files):

![image](https://user-images.githubusercontent.com/11148726/118380229-108a6200-b5d8-11eb-8eed-ccab4942c0e7.png)

**Comment by mtreacy002** [comment]
Makes sense, @isabelcosta . @Manthan109 , I'll assign you to this now. Please refer to @isabelcosta suggestions on your approach to this issue 😉

**Comment by manthanguptaa** [comment]
@isabelcosta So, If I have understood right I have to add the file structure as I did in my project up to 2 levels and add this to the docusaurus documentation but on mentorship backend and not on bridge-in-tech backend?

**Comment by vj-codes** [comment]
@Manthan109 any updates?
