### ISSUE TITLE
Update organization name from AnitaB.org to anitab-org in docusaurus config

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#291]
### Is your feature request related to a problem? Please describe.
Currently, the org name in docusaurus is Anitab.org but the GitHub name of the org is anitab-org
Changing the name will successfully deploy docusaurus to the gh pages

### Describe the solution you'd like
Change name as suggested above

### Describe alternatives you've considered
No alternative

**Comment by vj-codes** [comment]
@mtreacy002 I would like to work on this! 
[check reference here](https://github.com/anitab-org/bridge-in-tech-backend/pull/280#issuecomment-864409309)

**Comment by mtreacy002** [comment]
Assigning you, @vj-codes 😉
