### ISSUE TITLE
Update github email and name in documentation workflow

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#300]
### Is your feature request related to a problem? Please describe.
In the documentation workflow, the email and name are not updated with respect to the organization which is against what is mentioned on the official docusaurus website.
(Read the warning message in the screenshot)

![Screenshot (74)](https://user-images.githubusercontent.com/60894542/133677201-81d7f678-1512-4e64-ac73-74cd324b4405.png)

### Describe the solution you'd like
Update email and name

**Comment by vj-codes** [comment]
@mtreacy002 this might be the reason we can't see the homepage after deployment 
I would like to work on this :)

**Comment by isabelcosta** [comment]
its your @vj-codes  ;)
