### ISSUE TITLE
Setup: Wiki on BIT Environment Setup instructions

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#43]
## Description
As a student,
I need the project to have Set Up instructions on README.md,
so that I can help others setting up their environment to work on the project.

## Mocks
NA

### Update [Required]
**Must have the instructions to:**
- [ ]  [fork, clone remote](https://github.com/anitab-org/bridge-in-tech-backend/wiki/Fork,-Clone-&-Remote) bridge-in-tech-backend repository (by making use of the link given here 😄 )
- [ ] create a virtual environment
- [ ] create a PostgreSQL main local database with the name of **bit_schema**
        - [ ] create a second schema inside bit_schema and name it **bitschema** (first one is named `public` schema by default - leave it). So finally you should have two schemas - public and bitschema

- [ ] create another PostgreSQL local database for testing purpose and name it **bit_schema_test**
       - [ ]  the bit_schema_test **MUST HAVE** the 3 other schemas beside its `public` schema: **bit_schema**, **test_schema**, and **test_schema_2**

- [ ] add migration script to support any db models future changes
 
- [ ] run the application

- [ ] Must show that the required tables inside the **bit_schema** database are created successfully. To confirm, the tables are:
      - [ ] Under **public** schema:
              * users
              * mentorship_relations
              * tasks_list
              * tasks_comments
       - [ ] Under  **bitschema**:
               * users_extension
               * personal_backgrounds
               * organizations
               * programs
               * mentorship_relations_extension     

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by meenakshi-dhanani** [comment]
Maybe you can specify details here and mark it as a first timer issue for
someone to pick up :)

**Comment by mtreacy002** [comment]
> Maybe you can specify details here and mark it as a first timer issue for someone to pick up :)
> […](#)

Great idea. Will do that 😁

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . Created [Wiki page ](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup) instead for this issue (too big to put setup instructions inside README)

**Comment by mtreacy002** [comment]
Is it ok if we close this issue now, @anitab-org/bridgeintech-maintainers, as I already added the Wiki page directly on the repo. No PR needed for this issue.

**Comment by foongminwong** [comment]
@mtreacy002 yes, you can close it

**Comment by mtreacy002** [comment]
Thanks, @foongminwong .
