### ISSUE TITLE
Setup Travis CI to run tests for BIT backend

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-backend#44]
## Description
As a developer,
I need run tests on every PR on CI,
so that I can immediately get feedback on a build

## Out of Scope
Deploying to a higher environment when the push is on the develop branch

## Acceptance Criteria
- [ ] Build gets triggered on push
- [ ] Tests run for build

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
1-2 hours

**Comment by mtreacy002** [comment]
Update.
@anitab-org/bridgeintech-maintainers, as discussed with @meenakshi-dhanani and @ramitsawhney27 on [zulip](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Troubleshoot/near/199865779). The travis file will be taken care of directly under [PR#26](https://github.com/anitab-org/bridge-in-tech-backend/pull/26), the basic setup for backend dev. This issue can be closed now 😉
