### ISSUE TITLE
Development: Create Login API

### ISSUE THREAD

**Issue by ramitsawhney27** [anitab-org/bridge-in-tech-backend#47]
Description
As a student, I need to have the ability to login to BIT. For this the API on the backend should be available.
Mocks
NA

Acceptance Criteria
Create an API for user login for the BIT backend. The API would take a username/password combination as input and return a response code based on the validity of the data in the database. Majorly, 2 outcomes are possible: Successful (200 OK), or Unsuccessful (40x) (x represents one of the error codes like 400, 403, etc.)

Alternatives for testing the API: CuRL/Python requests

Update [Required]
Flask POST request for user login
 Takes user attributes as a json (eventually this will be sent through the UI)
 Response handling: 200 (Successful Process), 401 (unauthorized), 403 (forbidden), 400 (bad request), 500 (internal server error)
 Test the API using Postman (or any alternative)
Enhancement to Update [Optional]
Definition of Done
 All of the required items are completed.
 Approval by 2 mentors.

**Comment by mtreacy002** [comment]
@ramitsawhney27 . Just want to confirm.
For success Login response, we want it to be 200 OK not 201 Created, as per discussed in the [Proposal Review document](https://docs.google.com/document/d/1uCDCWs8Xyo-3EaUnrLOs48mefXJIN235b1aAswA-s-Y/edit#heading=h.qmolxjuwxlum). Am I right?

<img width="561" alt="Screen Shot 2020-06-19 at 9 30 13 pm" src="https://user-images.githubusercontent.com/29667122/85128301-5463d280-b274-11ea-83e3-f20517fde7b4.png">
