### ISSUE TITLE
Doc: Add missing images to BIT setup instructions Create main database section

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#53]
## Description
As a contributor,
I need to be able to see visual examples on how to setup my environment,
so that I can setup BridgeInTech backend development successfully.

## Mocks
The image below shows the missing images on [BIT Development Environment Setup Instructions](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup) wiki page.
<img width="610" alt="Screen Shot 2020-06-14 at 10 38 02 pm" src="https://user-images.githubusercontent.com/29667122/84593480-cf517580-ae8f-11ea-9103-5a33032f6fab.png">

### Update [Required]
- [ ] provide the images described in the `TO DO` on the places shown on the image above. The changes is to be placed in the ENV_SETUP_INSTRUCTION.md inside .github folder (the first one below line 27 and the other below line 31 of the .md file).

### Enhancement to Update [Optional]
NA
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by ramitsawhney27** [comment]
Approved

**Comment by VolatianaYuliana** [comment]
Hi @mtreacy002 
I would like to work on this one.

**Comment by mtreacy002** [comment]
Suree, @VolatianaYuliana . I'll assign you to this now. Thanks for picking up the issue 😉

**Comment by VolatianaYuliana** [comment]
Hey @mtreacy002!
On the **3rd step: Create the main Database**, there's that assertion after task number 5 that I should see two schemas. I don't understand where came from the public schema mentioned there because we just created **bitschema** schema in step 4.

**Comment by mtreacy002** [comment]
@VolatianaYuliana , this is because `public` schema is a default schema in postgresql and always automatically created when a database is created. This means, before adding `bitschema`, you can already see `'public` schema when you created a database. Creating another schema (in this case `bitschema`) will add as the 2nd schema of that database.

**Comment by VolatianaYuliana** [comment]
@mtreacy002  it makes sense thanks :)
