### ISSUE TITLE
Doc: Add link to Bridge In Tech Setup Instructions

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#55]
@mtreacy002 commented on [Sun Jun 14 2020](https://github.com/anitab-org/bridge-in-tech-web/issues/19)

## Description
As a contributor,
I need to see a link on the README file to where I can read setup instruction for development environment of Bridge In Tech backend,
so that I can contribute to the project.

## Mocks
NA
### Update [Required]
- [ ] Add a link with necessary description on README.md to go to BridgeInTech Development Environment Setup Instructions which can be found on bridge-in-tech-backend wiki repository.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
< 1 hour

---

@mahakbansal2019 commented on [Mon Jun 15 2020](https://github.com/anitab-org/bridge-in-tech-web/issues/19#issuecomment-643786599)

Hey @mtreacy002!
Can I work on this ?
Thanks :)

---

@mtreacy002 commented on [Mon Jun 15 2020](https://github.com/anitab-org/bridge-in-tech-web/issues/19#issuecomment-643900084)

Sure, go ahead, @mahakbansal2019 . Let me know if you need any help. Also, I'll move this issue to backend. I put it on frontend by accident. So, please add the link to the bridge-in-tech-backend repository README.md, not frontend 😉

**Comment by mahakbansal2019** [comment]
@mtreacy002 I'm not able to find bridge-in-tech-backend wiki repository.
Can you help me !
Thanks :)

**Comment by mtreacy002** [comment]
It's the same link I placed on the frontend PR. Here it is https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup
can you open the link?

**Comment by mahakbansal2019** [comment]
Yeah!
Thanks for the link. It was not visible on frontend PR :)

**Comment by mtreacy002** [comment]
I see. Please do put it inside the Backend Wiki, not the frontend one 😁

**Comment by mahakbansal2019** [comment]
@mtreacy002 Could you please review this?
Thanks :)
