### ISSUE TITLE
Development: Create/Update a profile on BIT

### ISSUE THREAD

**Issue by ramitsawhney27** [anitab-org/bridge-in-tech-backend#62]
**Is your feature request related to a problem? Please describe.**
As a student, I need to have the ability to create a profile on BIT. For this the API on the backend should be available.

**Describe the solution you'd like**
Create an API for profile creation/updation for the BIT backend. The API would take profile detail combinations as input and return a response code based on the validity of the data in the profile information. Majorly, 2 outcomes are possible: Successful (200 OK), or Unsuccessful (40x) (x represents one of the error codes like 400, 403, etc.), Not found (404), 500 (internal server error)

**Comment by mtreacy002** [comment]
Fixed with #78, #80, #82, #84, #86
