### ISSUE TITLE
Development: Get User profile

### ISSUE THREAD

**Issue by ramitsawhney27** [anitab-org/bridge-in-tech-backend#63]
**Is your feature request related to a problem? Please describe.**
I need to have the ability to retrieve a profile on BIT. For this, the API on the backend should be available.

**Describe the solution you'd like**
Create an API for user profile retrieval for the BIT backend. The API would take user id or information as input and return the profile information with the appropriate respnse.. Majorly, 2 outcomes are possible: Successful (200 OK), or Unsuccessful (40x) (x represents one of the error codes like 400, 403, etc.), Not found (404), 500 (internal server error)

The response should be a LIST, which will return all users if no filtering condition is provided, and a subset of users (even 1) as a list if a condition is supplied.

The GET request should take a parameter (for ex: user id, or username) that will be used to decide which users should be returned.

**Comment by ramitsawhney27** [comment]
@mtreacy002 - Please feel free to subdivide and break this issue into 3 issues (if you would like) for the following endpoints as per https://docs.google.com/document/d/1uCDCWs8Xyo-3EaUnrLOs48mefXJIN235b1aAswA-s-Y/edit#heading=h.qmolxjuwxlum
GET /users
GET /user
GET /users/{user_id}

**Comment by meenakshi-dhanani** [comment]
I'm cleaning up Zenhub a bit. I see a PR merged with respect to /user/personal_details. So can I move this story to done? and close this?

**Comment by mtreacy002** [comment]
Fixed with #76, #78, #82, #84
